---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= BlueXP 분류에 대한 질문과 대답
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== BlueXP 분류 서비스

다음 질문은 BlueXP 분류에 대한 일반적인 이해를 제공합니다.



=== BlueXP 분류는 어떻게 작동합니까?

BlueXP  분류를 통해 BlueXP  시스템 및 스토리지 시스템과 함께 또 다른 AI 계층을 구축합니다. 그런 다음 볼륨, 버킷, 데이터베이스 및 기타 스토리지 계정의 데이터를 검색하고 검색된 데이터 인사이트를 인덱싱합니다. BlueXP 분류는 정규식과 패턴 일치를 기반으로 일반적으로 구축되는 대체 솔루션과 달리 인공 지능과 자연어 처리를 모두 활용합니다.

BlueXP 분류에서는 AI를 사용하여 정확한 탐지 및 분류를 위해 데이터에 대한 상황별 이해를 제공합니다. AI는 최신 데이터 유형과 규모에 맞게 설계되었으므로 AI를 중심으로 구동됩니다. 또한 데이터 컨텍스트를 이해하여 강력하고 정확한 검색 및 분류를 제공합니다.

link:concept-cloud-compliance.html["BlueXP 분류의 작동 방식에 대해 자세히 알아보십시오"]..



=== BlueXP 분류에는 REST API가 있으며 타사 도구와 작동합니까?

예. BlueXP  분류에는 BlueXP  코어 플랫폼의 일부인 BlueXP  분류 버전에서 지원되는 기능에 대한 REST API가 있습니다. 을 link:api-classification.html["API 설명서"]참조하십시오.



=== 클라우드 마켓플레이스를 통해 BlueXP  분류를 사용할 수 있습니까?

BlueXP  분류는 BlueXP  핵심 기능의 일부이므로 이 서비스에 마켓플레이스를 사용할 필요가 없습니다.



== BlueXP 분류 스캔 및 분석

다음 질문은 BlueXP  분류 스캔 성능 및 분석과 관련이 있습니다.



=== BlueXP 분류는 내 데이터를 얼마나 자주 검사합니까?

데이터의 초기 스캔에는 시간이 다소 걸릴 수 있지만 후속 스캔에서는 증분 변경 내용만 검사하므로 시스템 검사 시간이 단축됩니다. BlueXP 분류는 데이터를 라운드 로빈 방식으로 지속적으로 스캔하므로 변경된 모든 데이터를 매우 빠르게 분류할 수 있습니다.

link:task-scanning-overview.html["스캔 작동 방식에 대해 알아보십시오"]..

BlueXP  분류는 하루에 한 번만 데이터베이스를 스캔합니다. 데이터베이스는 다른 데이터 소스와 마찬가지로 지속적으로 스캔되지 않습니다.

데이터 스캔은 스토리지 시스템과 데이터에 경미한 영향을 줍니다.



=== 스캔 성능이 달라집니까?

스캔 성능은 네트워크 대역폭 및 환경의 평균 파일 크기에 따라 달라질 수 있습니다. 또한 호스트 시스템의 크기 특성(클라우드 또는 온프레미스)에 따라 달라질 수 있습니다. link:concept-cloud-compliance.html["BlueXP 분류 인스턴스입니다"]자세한 내용은 및 link:task-deploy-overview.html["BlueXP 분류 배포"] 를 참조하십시오.

새 데이터 소스를 처음 추가할 때 전체 "분류"(지도 및 분류) 스캔 대신 "매핑"(매핑만) 스캔만 수행하도록 선택할 수도 있습니다. 내부 데이터를 보기 위해 파일에 액세스하지 않기 때문에 데이터 소스에서 매핑을 매우 빠르게 수행할 수 있습니다. link:task-scanning-overview.html["매핑 스캔과 분류 스캔의 차이를 확인하십시오"]..



=== BlueXP 분류를 사용하여 데이터를 검색할 수 있습니까?

BlueXP 분류는 연결된 모든 소스에서 특정 파일 또는 데이터 조각을 쉽게 검색할 수 있는 광범위한 검색 기능을 제공합니다. BlueXP 분류는 메타데이터의 반사보다 더 깊이 있는 검색을 가능하게 합니다. 또한 파일을 읽고 이름 및 ID와 같은 여러 가지 중요한 데이터 형식을 분석할 수 있는 언어 독립적인 서비스입니다. 예를 들어, 사용자는 정형 데이터 저장소와 비정형 데이터 저장소 모두를 검색하여 데이터베이스에서 사용자 파일로 유출되었을 수 있는 데이터를 찾을 수 있습니다. 이는 기업 정책에 위배됩니다. 검색을 나중에 저장할 수 있으며, 설정된 빈도로 검색 및 결과에 대한 조치를 취하기 위해 정책을 생성할 수 있습니다.

관심 파일이 발견되면 태그, 작업 환경 계정, 버킷, 파일 경로, 범주(분류 기준), 파일 크기, 마지막 수정, 권한 상태, 중복, 감도 수준, 개인 데이터, 파일 내 중요 데이터 유형, 소유자, 파일 유형, 파일 크기, 생성 시간, 파일 해시, 해당 데이터가 관심을 원하는 사람에게 할당되었는지 여부 등 필터는 관련이 없는 특성을 선별하는 데 적용할 수 있습니다.

또한 BlueXP  분류에는 RBAC(역할 기반 액세스 제어)가 있어 올바른 권한이 있는 경우 파일을 이동하거나 삭제할 수 있습니다. 올바른 사용 권한이 없으면 조직에 있는 사용자에게 적절한 사용 권한이 있는 작업을 할당할 수 있습니다.



== BlueXP 분류 관리 및 개인 정보 보호

다음 질문에서는 BlueXP 분류 및 개인 정보 보호 설정을 관리하는 방법에 대한 정보를 제공합니다.



=== BlueXP  분류를 활성화 또는 비활성화하려면 어떻게 합니까?

먼저 BlueXP 또는 사내 시스템에 BlueXP 분류 인스턴스를 배포해야 합니다. 인스턴스가 실행되면 * Configuration * 탭에서 기존 작업 환경, 데이터베이스 및 기타 데이터 원본에 대한 서비스를 활성화하거나 특정 작업 환경을 선택할 수 있습니다. link:task-getting-started-compliance.html["시작하는 방법을 알아보십시오"]..


NOTE: 데이터 소스에서 BlueXP 분류를 활성화하면 즉시 초기 검사가 이루어집니다. 스캔 결과는 잠시 후에 표시됩니다.

BlueXP 분류 구성 페이지에서 개별 작업 환경, 데이터베이스 또는 파일 공유 그룹을 스캔하는 데 BlueXP 분류를 사용하지 않도록 설정할 수 있습니다. 을 link:task-managing-compliance.html["BlueXP 분류에서 데이터 소스를 제거합니다"]참조하십시오.

BlueXP 분류 인스턴스를 완전히 제거하려면 클라우드 공급자의 포털 또는 사내 위치에서 BlueXP 분류 인스턴스를 수동으로 제거할 수 있습니다.



=== 서비스가 특정 디렉터리에서 스캔 데이터를 제외할 수 있습니까?

예. BlueXP 분류를 통해 특정 데이터 소스 디렉토리에 있는 스캔 데이터를 제외하려면 해당 목록을 분류 엔진에 제공할 수 있습니다. 변경 사항을 적용하면 BlueXP 분류에서 지정된 디렉토리에 있는 검사 데이터를 제외합니다. link:task-exclude-scan-paths.html["자세한 정보"]..



=== ONTAP 볼륨에 상주하는 스냅샷이 스캔됩니까?

아니요. BlueXP  분류는 컨텐츠가 볼륨의 컨텐츠와 동일하기 때문에 스냅샷을 스캔하지 않습니다.



=== ONTAP 볼륨에서 데이터 계층화가 활성화된 경우 어떻게 됩니까?

BlueXP  분류에서는 매핑 전용 검사를 사용하여 콜드 데이터가 오브젝트 스토리지로 계층화된 볼륨을 스캔하면 로컬 디스크에 있는 데이터와 오브젝트 스토리지로 계층화된 콜드 데이터가 포함된 모든 데이터를 검사합니다. 이는 계층화를 구현하는 NetApp 제품이 아닌 경우에도 마찬가지입니다.

Mapping Only(매핑 전용) 스캔은 콜드 데이터를 가열하지 않습니다. 즉, 콜드 데이터는 객체 스토리지에 남아 있습니다. 반면에 Map & Classify(맵 및 분류) 스캔을 수행하면 일부 구성이 콜드 데이터를 가열할 수 있습니다.



== 소스 시스템 및 데이터 유형의 유형입니다

다음 질문은 스캔할 수 있는 스토리지 유형 및 스캔할 데이터 유형과 관련되어 있습니다.



=== 정부 지역에 배포할 때 제한 사항이 있습니까?

커넥터가 정부 지역(AWS GovCloud, Azure Gov 또는 Azure DoD)에 배포되어 "제한 모드"라고도 하는 경우 BlueXP 분류가 지원됩니다.



=== 인터넷 액세스 없이 사이트에 BlueXP 분류를 설치할 경우 어떤 데이터 소스를 검색할 수 있습니까?

BlueXP 분류는 사내 사이트에 로컬인 데이터 소스에서만 데이터를 스캔할 수 있습니다. 현재 BlueXP 분류는 "비공개 모드"에서 "다크" 사이트라고도 하는 다음 로컬 데이터 소스를 검사할 수 있습니다.

* 온프레미스 ONTAP 시스템
* 데이터베이스 스키마
* S3(Simple Storage Service) 프로토콜을 사용하는 오브젝트 스토리지


을 link:concept-cloud-compliance.html["지원되는 작업 환경 및 데이터 소스"]참조하십시오.



=== 지원되는 파일 유형은 무엇입니까?

BlueXP 분류는 모든 파일에서 범주 및 메타데이터 정보를 검색하고 대시보드의 파일 형식 섹션에 모든 파일 형식을 표시합니다.

BlueXP 분류에서 PII(개인 식별 정보)를 감지하거나 DSAR 검색을 수행할 때 다음 파일 형식만 지원됩니다.

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== BlueXP 분류 체계는 어떤 종류의 데이터와 메타데이터를 캡처합니까?

BlueXP 분류를 통해 데이터 소스에서 일반적인 "매핑" 스캔 또는 전체 "분류" 스캔을 실행할 수 있습니다. 매핑은 데이터에 대한 상위 수준의 개요만 제공하는 반면 분류는 데이터에 대한 세부 수준의 스캐닝을 제공합니다. 내부 데이터를 보기 위해 파일에 액세스하지 않기 때문에 데이터 소스에서 매핑을 매우 빠르게 수행할 수 있습니다.

* * 데이터 매핑 스캔 (매핑 전용 스캔) * : BlueXP  분류는 메타데이터만 스캔합니다. 이 기능은 전체 데이터 관리 및 거버넌스, 빠른 프로젝트 범위 지정, 대규모 부동산 및 우선순위 지정에 유용합니다. 데이터 매핑은 메타데이터를 기반으로 하며 * 빠른 * 스캔으로 간주됩니다.
+
고속 스캔 후 데이터 매핑 보고서를 생성할 수 있습니다. 이 보고서는 리소스 활용도, 마이그레이션, 백업, 보안 및 규정 준수 프로세스에 대한 의사 결정을 돕기 위해 기업 데이터 소스에 저장된 데이터에 대한 개요입니다.

* * 데이터 분류(심층) 스캔(지도 및 분류 스캔) *: 사용자 환경 전반에서 표준 프로토콜과 읽기 전용 권한을 사용하여 BlueXP  분류 스캔. Select 파일은 랜섬웨어 관련 중요 비즈니스 관련 데이터, 개인 정보 및 문제를 대상으로 열렸다 스캔됩니다.
+
전체 스캔 후에는 데이터 조사 페이지의 데이터 보기 및 구체화, 파일 내 이름 검색, 복사, 이동, 원본 파일 삭제 등 데이터에 적용할 수 있는 여러 가지 BlueXP 분류 기능이 추가로 있습니다.



BlueXP 분류는 파일 이름, 권한, 생성 시간, 마지막 액세스, 마지막 수정과 같은 메타데이터를 캡처합니다. 여기에는 Data Investigatcdion Details 페이지 및 Data Investigation Reports에 나타나는 모든 메타데이터가 포함됩니다.

BlueXP  분류는 개인 정보(PII) 및 민감한 개인 정보(SPII) 등 다양한 유형의 개인 데이터를 식별할 수 있습니다. 개인 데이터에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["BlueXP 분류가 검사하는 프라이빗 데이터의 범주입니다"]참조하십시오.



=== 특정 사용자에게 BlueXP 분류 정보를 제한할 수 있습니까?

예. BlueXP 분류는 BlueXP와 완전히 통합되어 있습니다. BlueXP  사용자는 사용 권한에 따라 볼 수 있는 작업 환경에 대한 정보만 볼 수 있습니다.

또한 특정 사용자가 BlueXP  분류 설정을 관리할 수 없는 상태에서 BlueXP  분류 스캔 결과를 볼 수 있도록 허용하려면 해당 사용자에게 * 분류 뷰어 * 역할(표준 모드에서 BlueXP  사용 시) 또는 * 규정 준수 뷰어 * 역할(제한 모드에서 BlueXP  사용 시)을 할당할 수 있습니다. link:concept-cloud-compliance.html["자세한 정보"]..



=== 내 브라우저와 BlueXP 분류 간에 전송되는 개인 데이터에 누구나 액세스할 수 있습니까?

아니요. 브라우저와 BlueXP  분류 인스턴스 간에 전송되는 개인 데이터는 TLS 1.2를 사용하여 엔드 투 엔드 암호화로 보호됩니다. 즉, NetApp 및 비 NetApp 당사자가 읽을 수 없습니다. BlueXP 분류는 액세스를 요청하고 승인하지 않는 한 NetApp과 데이터 또는 결과를 공유하지 않습니다.

스캔되는 데이터는 사용자 환경 내에 유지됩니다.



=== 중요 데이터는 어떻게 처리됩니까?

NetApp는 중요한 데이터에 액세스할 수 없으며 UI에 이를 표시하지 않습니다. 중요한 데이터는 마스킹됩니다. 예를 들어, 마지막 4개의 숫자는 신용 카드 정보로 표시됩니다.



=== 데이터가 어디에 저장됩니까?

스캔 결과는 BlueXP 분류 인스턴스 내의 Elasticsearch에 저장됩니다.



=== 데이터에 어떻게 액세스됩니까?

BlueXP 분류는 API 호출을 통해 Elasticsearch에 저장된 데이터에 액세스하며, 인증이 필요하며 AES-128을 사용하여 암호화됩니다. Elasticsearch에 직접 액세스하려면 루트 액세스가 필요합니다.



== 추가 수익 실적을

다음 질문은 BlueXP 분류를 사용하기 위한 라이센스 및 비용과 관련됩니다.



=== BlueXP 분류 비용은 얼마입니까?

BlueXP 분류는 BlueXP 핵심 기능이며 비용이 청구되지 않습니다.



== 커넥터 전개

다음 질문은 BlueXP 커넥터와 관련이 있습니다.



=== 커넥터란 무엇입니까?

Connector는 클라우드 계정 또는 온프레미스 컴퓨팅 인스턴스에서 실행되는 소프트웨어로, BlueXP에서 클라우드 리소스를 안전하게 관리할 수 있도록 지원합니다. BlueXP 분류를 사용하려면 커넥터를 배포해야 합니다.



=== 커넥터를 어디에 설치해야 합니까?

데이터를 스캔할 때는 다음 위치에 BlueXP  커넥터를 설치해야 합니다.

* AWS 또는 Amazon FSx for ONTAP의 경우 Cloud Volumes ONTAP: 커넥터가 AWS에 있습니다.
* Azure 또는 Azure NetApp Files의 Cloud Volumes ONTAP: 커넥터가 Azure에 있습니다.
* GCP의 Cloud Volumes ONTAP용: 커넥터가 GCP에 있습니다.
* 온프레미스 ONTAP 시스템의 경우: 커넥터는 온-프레미스입니다.


이러한 위치에 데이터가 있는 경우 을 사용해야 할 수 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["다중 커넥터"^] 있습니다.



=== BlueXP 분류를 수행하려면 자격 증명에 액세스해야 합니까?

BlueXP 분류 자체는 스토리지 자격 증명을 검색하지 않습니다. BlueXP Connector에 저장됩니다.

BlueXP 분류에서는 스캔 전에 CIFS 자격 증명을 사용하여 공유를 마운트하는 등의 데이터 플레인 자격 증명을 사용합니다.



=== 서비스와 커넥터 간의 통신이 HTTP를 사용합니까?

예, BlueXP 분류는 HTTP를 사용하여 BlueXP Connector와 통신합니다.



== BlueXP 분류 구축

다음 질문은 별도의 BlueXP 분류 인스턴스와 관련이 있습니다.



=== BlueXP 분류 기능은 어떤 배포 모델을 지원합니까?

BlueXP를 사용하면 온프레미스, 클라우드 및 하이브리드 환경을 비롯한 거의 모든 곳에서 시스템을 검색하고 보고할 수 있습니다. 일반적으로 BlueXP 분류는 서비스를 BlueXP 인터페이스를 통해 사용할 수 있고 하드웨어나 소프트웨어를 설치할 필요가 없는 SaaS 모델을 사용하여 배포됩니다. 이처럼 클릭-앤-런 구축 모드에서도 데이터 저장소가 온프레미스에 있든 퍼블릭 클라우드에 있든 상관없이 데이터 관리를 수행할 수 있습니다.



=== BlueXP 분류에 필요한 인스턴스 또는 VM 유형은 무엇입니까?

언제link:task-deploy-cloud-compliance.html["클라우드에 구축"]:

* AWS에서 BlueXP 분류는 500GiB GP2 디스크가 있는 m6i.4xLarge 인스턴스에서 실행됩니다. 배포 중에 더 작은 인스턴스 유형을 선택할 수 있습니다.
* Azure에서 BlueXP 분류는 500GiB 디스크를 사용하는 Standard_D16s_v3 VM에서 실행됩니다.
* GCP에서 BlueXP 분류는 500GiB 표준 영구 디스크를 사용하는 n2-standard-16 VM에서 실행됩니다.


link:concept-cloud-compliance.html["BlueXP 분류의 작동 방식에 대해 자세히 알아보십시오"]..



=== 자체 호스트에 BlueXP 분류를 배포할 수 있습니까?

예. 네트워크 또는 클라우드에서 인터넷에 액세스할 수 있는 Linux 호스트에 BlueXP 분류 소프트웨어를 설치할 수 있습니다. 모든 기능이 동일하며 BlueXP를 통해 스캔 구성 및 결과를 계속 관리할 수 있습니다. 시스템 요구 사항 및 설치에 대한 자세한 내용은 을 link:task-deploy-compliance-onprem.html["구내 BlueXP 분류 배포"]참조하십시오.



=== 인터넷에 연결되지 않은 보안 사이트는 어떻게 됩니까?

예, 지원합니다. 완벽한 보안 사이트를 만들 수 link:task-deploy-compliance-dark-site.html["인터넷에 액세스할 수 없는 사내 사이트에 BlueXP 분류를 배포합니다"]있습니다.
