---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, bluexp, scan shares 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



== BlueXP 분류 릴리스에 옵션이 제거되었습니다

2023년 12월(버전 1.26.6) 릴리즈에서는 다음 옵션이 제거되었습니다.

* 감사 로그 수집을 활성화하는 옵션이 비활성화되었습니다.
* 디렉터리 조사 중에는 디렉터리별 개인 식별 정보(PII) 데이터 수를 계산하는 옵션을 사용할 수 없습니다.
* AIP(Azure Information Protection) 레이블을 사용하여 데이터를 통합하는 옵션이 비활성화되었습니다.




== BlueXP 분류 스캔 제한



=== BlueXP 분류 기능은 볼륨 아래에서 하나의 공유만 검색합니다

단일 볼륨 아래에 여러 파일 공유가 있는 경우 BlueXP 분류는 가장 높은 계층 구조로 공유를 검색합니다. 예를 들어 다음과 같은 공유가 있는 경우

* /A
* /A/B
* /C
* /D/E


그러면 /A의 데이터가 스캔됩니다. /C 및 /D의 데이터는 스캔되지 않습니다.

.해결 방법
볼륨에 있는 모든 공유에서 데이터를 스캔하도록 하는 해결 방법이 있습니다. 다음 단계를 수행하십시오.

. 작업 환경에서 스캔할 볼륨을 추가합니다.
. BlueXP 분류가 볼륨 스캔을 완료한 후 _Data Investigation_page로 이동하여 어떤 공유가 스캔되고 있는지 확인하기 위한 필터를 생성합니다.
+
"작업 환경 이름" 및 "디렉터리 유형 = 공유"로 데이터를 필터링하여 스캔할 공유를 확인할 수 있습니다.

. 볼륨에 있는 공유의 전체 목록을 받아 스캔하지 않는 공유를 확인할 수 있습니다.
. link:task-scanning-file-shares.html["나머지 공유를 공유 그룹에 추가합니다"].
+
모든 공유를 개별적으로 추가해야 합니다. 예를 들면 다음과 같습니다.

+
....
/C
/D
....
. 여러 공유가 있는 작업 환경의 각 볼륨에 대해 다음 단계를 수행합니다.

