---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: BlueXP 분류는 BlueXP 분류가 검색하는 모든 작업 환경 및 데이터 소스의 파일에 대해 수행된 관리 작업을 기록합니다. 또한 BlueXP 분류는 BlueXP 분류 인스턴스를 배포할 때 작업을 기록합니다. 
---
= BlueXP 분류 작업의 이력을 감사합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 분류는 BlueXP 분류가 검색하는 모든 작업 환경 및 데이터 소스의 파일에 대해 수행된 관리 작업을 기록합니다. 또한 BlueXP 분류는 BlueXP 분류 인스턴스를 배포할 때 작업을 기록합니다.

BlueXP 분류 감사 로그 파일의 내용을 보거나 다운로드하여 어떤 파일 변경 사항이 발생했는지, 언제 변경되었는지 확인할 수 있습니다. 예를 들어, 어떤 요청이 실행되었는지, 요청 시간, 파일이 삭제된 경우 소스 위치 등의 세부 정보 또는 파일이 이동된 경우 소스 및 대상 위치를 확인할 수 있습니다.

[]
====
* 참고 * 이 정보는 BlueXP  분류 레거시 버전 1.30 이하에만 해당됩니다.

====


== 로그 파일 내용

감사 로그의 각 줄에는 다음 형식의 정보가 포함되어 있습니다.

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* 날짜 및 시간 - 이벤트의 전체 타임 스탬프입니다
* 상태 - 정보, 경고
* 작업 유형(삭제, 복사, 이동, 정책 생성, 정책 업데이트, 파일 재검색, JSON 보고서 다운로드 등)
* 파일 이름(작업이 파일과 관련된 경우)
* 작업에 대한 세부 정보 - 수행한 작업: 작업에 따라 다릅니다
+
** 정책 이름입니다
** 이동 - 원본 및 대상
** 복사 - 원본 및 대상
** 태그-태그 이름용
** 사용자 이름으로 할당
** 전자 메일 알림의 경우 - 전자 메일 주소/계정입니다




예를 들어, 로그 파일의 다음 줄은 성공적인 복사 작업과 실패한 복제 작업을 보여 줍니다.

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== 로그 파일 위치

관리 감사 로그 파일은 BlueXP  분류 시스템의 다음 위치에 있습니다. `/opt/netapp/audit_logs/`

설치 감사 로그 파일이 에 기록됩니다 `/opt/netapp/install_logs/`

각 로그 파일의 크기는 최대 10MB입니다. 이 제한에 도달하면 새 로그 파일이 시작됩니다. 로그 파일의 이름은 "DataSense_audit.log", "DataSense_audit.log.1", "DataSense_audit.log.2" 등으로 지정됩니다. 시스템에 최대 100개의 로그 파일이 보존됩니다. 오래된 로그 파일은 최대 로그 수에 도달하면 자동으로 삭제됩니다.



== 로그 파일에 액세스합니다

로그 파일에 액세스하려면 BlueXP 분류 시스템에 로그인해야 합니다. Linux 시스템에 소프트웨어를 수동으로 설치했는지 또는 클라우드에 인스턴스를 배포했는지 여부에 따라 에 대해 link:reference-log-in-to-instance.html["BlueXP 분류 시스템에 로그인합니다"]알아봅니다.
