---
sidebar: sidebar 
permalink: task-deploy-multi-host-install-dark-site.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, web browser connectivity, cloud compliance access, privacy, compliance, on-premises, dark site, upgrade, private mode, docker, podman, bluexp classification, classification, install 
summary: '"비공개 모드"라고도 하는 인터넷 액세스가 없는 사내 사이트의 Linux 호스트에 BlueXP 분류를 설치하려면 몇 가지 단계를 완료하십시오. 이러한 유형의 설치는 보안 사이트에 적합합니다.' 
---
= 인터넷에 액세스할 수 없는 대규모 구성을 위해 여러 호스트에 BlueXP 분류를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
인터넷에 액세스할 수 없는 온프레미스 사이트의 여러 호스트에 BlueXP 분류를 설치하려면 몇 단계를 완료하십시오. _ private mode _ 라고도 합니다. 이러한 유형의 설치는 보안 사이트에 적합합니다.

인터넷 액세스 없이 사이트에서 페타바이트 단위의 데이터를 검색할 수 있는 대규모 구성의 경우 여러 호스트를 포함시켜 처리 성능을 높일 수 있습니다. 여러 호스트 시스템을 사용하는 경우 주 시스템을 _Manager node_라고 하며 추가 처리 능력을 제공하는 추가 시스템을 _Scanner nodes_라고 합니다.

오프라인 환경의 여러 사내 호스트에 BlueXP 분류 소프트웨어를 설치할 때는 다음 단계를 따르십시오.


NOTE: 다음 정보는 BlueXP  분류 레거시 버전 1.30 이하에만 해당됩니다.

.시작하기 전에
* Manager 및 Scanner 노드용 모든 Linux 시스템이 호스트 요구 사항을 충족하는지 확인합니다.
* 두 가지 필수 소프트웨어 패키지(Docker Engine 또는 Podman 및 Python 3)를 설치했는지 확인합니다.
* Linux 시스템에 대한 루트 권한이 있는지 확인합니다.
* 오프라인 환경이 필요한 사용 권한 및 연결을 충족하는지 확인합니다.
* 사용하려는 스캐너 노드 호스트의 IP 주소가 있어야 합니다.
* 모든 호스트에서 다음 포트 및 프로토콜을 활성화해야 합니다.
+
[cols="15,20,55"]
|===
| 포트 | 프로토콜 | 설명 


| 2377 | TCP | 클러스터 관리 통신 


| 7946 | TCP, UDP | 노드 간 통신 


| 4789 | UDP입니다 | 오버레이 네트워크 트래픽 


| 50 | ESP | 암호화된 IPsec 오버레이 네트워크(ESP) 트래픽 


| 111 | TCP, UDP | 호스트 간 파일 공유를 위한 NFS 서버(각 스캐너 노드에서 관리자 노드로 필요) 


| 2049 | TCP, UDP | 호스트 간 파일 공유를 위한 NFS 서버(각 스캐너 노드에서 관리자 노드로 필요) 
|===


.단계
. 관리자 노드의 에서 1-8단계를 link:task-deploy-compliance-dark-site.html#single-host-installation-for-typical-configurations["단일 호스트 설치"]수행합니다.
. 9단계에서 설명한 것처럼 설치 관리자가 메시지를 표시하면 일련의 프롬프트에 필요한 값을 입력하거나 설치 프로그램에 명령줄 인수로 필요한 매개 변수를 제공할 수 있습니다.
+
단일 호스트 설치에 사용할 수 있는 변수 외에도 새 옵션 * -n<node_ip> * 를 사용하여 스캐너 노드의 IP 주소를 지정할 수 있습니다. 여러 노드 IP는 쉼표로 구분됩니다.

+
예를 들어, 이 명령은 3개의 스캐너 노드를 추가합니다.
`sudo ./install.sh -a <account_id> -c <client_id> -t <user_token> --host <ds_host> --manager-host <cm_host> *-n <node_ip1>,<node_ip2>,<node_ip3>* --no-proxy --darksite`

. 관리자 노드 설치가 완료되기 전에 스캐너 노드에 필요한 설치 명령이 대화 상자에 표시됩니다. 명령(예 `sudo ./node_install.sh -m 10.11.12.13 -t ABCDEF-1-3u69m1-1s35212`:)을 복사하여 텍스트 파일에 저장합니다.
. 켜짐 * 각 * 스캐너 노드 호스트:
+
.. Data Sense 설치 프로그램 파일(* cc_onpremise_installer.tar.gz *)을 호스트 컴퓨터에 복사합니다.
.. 설치 프로그램 파일의 압축을 풉니다.
.. 3단계에서 복사한 명령을 붙여 넣고 실행합니다.
+
모든 스캐너 노드에서 설치가 완료되고 관리자 노드에 연결되었으면 관리자 노드 설치도 완료됩니다.





.결과
BlueXP 분류 설치 프로그램이 패키지 설치를 완료하고 설치를 등록합니다. 설치에는 15 ~ 25분이 소요될 수 있습니다.

.다음 단계
구성 페이지에서 스캔할 로컬  및 로컬을 link:task-scanning-databases.html["데이터베이스를 지원합니다"]선택할 수 link:task-getting-started-compliance.html["온프레미스 ONTAP 클러스터"]있습니다.
