---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, data sense, get started, deploy, bluexp classification, cloud compliance access, compliance, on-premises, linux, test linux system, docker, podman, dark site 
summary: Linux 호스트에 수동으로 BlueXP 분류를 설치하기 전에 호스트에서 스크립트를 실행하여 BlueXP 분류를 설치하기 위한 모든 필수 구성 요소가 준비되어 있는지 확인할 수 있습니다. 이 스크립트는 네트워크의 Linux 호스트 또는 클라우드의 Linux 호스트에서 실행할 수 있습니다. 호스트를 인터넷에 연결할 수도 있고, 호스트가 인터넷에 액세스할 수 없는 사이트에 상주할 수도 있습니다. 
---
= Linux 호스트가 BlueXP 분류를 설치할 준비가 되었는지 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux 호스트에 수동으로 BlueXP 분류를 설치하기 전에 호스트에서 스크립트를 실행하여 BlueXP 분류를 설치하기 위한 모든 필수 구성 요소가 준비되어 있는지 확인할 수 있습니다. 이 스크립트는 네트워크의 Linux 호스트 또는 클라우드의 Linux 호스트에서 실행할 수 있습니다. 호스트를 인터넷에 연결하거나 호스트가 인터넷에 액세스할 수 없는 사이트(A_Dark site_)에 상주할 수 있습니다.

BlueXP 분류 설치 스크립트의 일부인 필수 테스트 스크립트도 있습니다. 여기에 설명된 스크립트는 BlueXP 분류 설치 스크립트를 실행하는 것과 독립적으로 Linux 호스트를 확인하려는 사용자를 위해 특별히 설계되었습니다.



== 시작하기

다음 작업을 수행합니다.

. BlueXP 커넥터가 아직 설치되지 않은 경우 설치할 수도 있습니다. Connector를 설치하지 않고 테스트 스크립트를 실행할 수 있지만 스크립트는 Connector와 BlueXP 분류 호스트 시스템 간의 연결을 검사하므로 Connector를 사용하는 것이 좋습니다.
. 호스트 시스템을 준비하고 모든 요구 사항을 충족하는지 확인합니다.
. BlueXP 분류 호스트 시스템에서 아웃바운드 인터넷 액세스를 활성화합니다.
. 모든 시스템에서 필요한 포트가 활성화되어 있는지 확인합니다.
. 사전 필수 테스트 스크립트를 다운로드하고 실행합니다.




== 커넥터를 작성합니다

BlueXP 분류를 설치하고 사용하려면 먼저 BlueXP 커넥터가 필요합니다. 그러나 커넥터 없이 필수 구성 요소 스크립트를 실행할 수 있습니다.

가능합니다 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["Connector On-Premises를 설치합니다"^] 네트워크의 Linux 호스트 또는 클라우드의 Linux 호스트 BlueXP 분류를 사내에서 설치하려는 일부 사용자는 Connector를 내부에 설치할 수도 있습니다.

클라우드 공급자 환경에 Connector를 만들려면 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["AWS에서 커넥터 생성"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Azure에서 커넥터 만들기"^], 또는 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["GCP에서 커넥터를 생성하는 중입니다"^].

필수 구성 요소 스크립트를 실행할 때는 커넥터 시스템의 IP 주소 또는 호스트 이름이 필요합니다. 이 정보는 구내에 Connector를 설치한 경우 확인할 수 있습니다. Connector가 클라우드에 배포된 경우 BlueXP 콘솔에서 이 정보를 찾을 수 있습니다. 도움말 아이콘을 클릭하고 * 지원 * 을 선택한 다음 * BlueXP 커넥터 * 를 클릭합니다.



== 호스트 요구 사항을 확인합니다

BlueXP 분류 소프트웨어는 특정 운영 체제 요구 사항, RAM 요구 사항, 소프트웨어 요구 사항 등을 충족하는 호스트에서 실행해야 합니다.

* BlueXP 분류는 다른 애플리케이션과 공유되는 호스트에서는 지원되지 않습니다. 호스트는 전용 호스트여야 합니다.
* 사내에 호스트 시스템을 구축할 때 BlueXP 분류 검사를 수행하려는 데이터 세트의 크기에 따라 3가지 시스템 크기 중에서 선택할 수 있습니다.
+
[cols="17,17,27,31"]
|===
| 시스템 크기 | CPU | RAM(스왑 메모리는 비활성화 상태여야 함) | 디스크 


| * 초대형 * | 32개의 CPU | 128GB RAM | /, 또는 의 1TiB SSD
/opt에서 -100GiB를 사용할 수 있습니다
-895GiB는 /var/lib/docker에서 사용할 수 있습니다
/tmp에 -5GiB입니다 


| * 대형 * | CPU 16개 | 64GB RAM | 500GiB SSD 켜짐/또는
/opt에서 -100GiB를 사용할 수 있습니다
-395GiB는 /var/lib/docker, Podman/var/lib/컨테이너 또는 Podman/var/lib/컨테이너에서 사용할 수 있습니다
/tmp에 -5GiB입니다 


| * 중간 * | CPU 8개 | 32GB RAM | 200GiB SSD 켜짐/또는
/opt에서 -50GiB를 사용할 수 있습니다
-145GiB는 /var/lib/docker 또는 Podman/var/lib/컨테이너에서 사용할 수 있습니다
/tmp에 -5GiB입니다 


| * 소형 * | CPU 8개 | 16GB RAM | 또는 에서 100GiB SSD
/opt에서 -50GiB를 사용할 수 있습니다
-45GiB는 /var/lib/docker 또는 Podman/var/lib/컨테이너에서 사용할 수 있습니다
/tmp에 -5GiB입니다 
|===
+
소형 시스템을 사용할 때는 제한이 있습니다. 을 참조하십시오 link:concept-cloud-compliance.html#using-a-smaller-instance-type["더 작은 인스턴스 유형 사용"] 를 참조하십시오.

* BlueXP 분류 설치를 위해 클라우드에 컴퓨팅 인스턴스를 배포할 때는 위의 "대규모" 시스템 요구 사항을 충족하는 시스템을 권장합니다.
+
** * Amazon Elastic Compute Cloud(Amazon EC2) 인스턴스 유형 *: "m6i.4xlarge"를 권장합니다. link:reference-instance-types.html#aws-instance-types["추가 AWS 인스턴스 유형을 참조하십시오"^].
** * Azure VM size *: "Standard_D16s_v3"을 권장합니다. link:reference-instance-types.html#azure-instance-types["추가 Azure 인스턴스 유형을 참조하십시오"^].
** * GCP 시스템 유형 *: "n2-standard-16"을 권장합니다. link:reference-instance-types.html#gcp-instance-types["추가 GCP 인스턴스 유형을 참조하십시오"^].


* UNIX 폴더 권한 *: 다음과 같은 최소 UNIX 권한이 필요합니다.
+
[cols="25,25"]
|===
| 폴더 | 최소 권한 


| /tmp | `rwxrwxrwt` 


| /opt | `rwxr-xr-x` 


| /var/lib/docker입니다 | `rwx------` 


| /usr/lib/systemd/system입니다 | `rwxr-xr-x` 
|===
* * 운영 체제 *:
+
** 다음 운영 체제에서는 Docker 컨테이너 엔진을 사용해야 합니다.
+
*** Red Hat Enterprise Linux 버전 7.8 및 7.9
*** CentOS 버전 7.8 및 7.9
*** Ubuntu 22.04(BlueXP 분류 버전 1.23 이상 필요)


** 다음 운영 체제에는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP 분류 버전 1.30 이상이 필요합니다.
+
*** Red Hat Enterprise Linux 버전 8.8, 9.0, 9.1, 9.2 및 9.3
+
RHEL 8.x 및 RHEL 9.x를 사용하는 경우 다음 기능은 현재 지원되지 않습니다.

+
**** 어두운 장소에 설치
**** 분산 스캔, 마스터 스캐너 노드 및 원격 스캐너 노드 사용






* * Red Hat 서브스크립션 관리 *: 호스트는 Red Hat 서브스크립션 관리 에 등록되어 있어야 합니다. 등록되지 않은 경우 설치 중에 시스템에서 필요한 타사 소프트웨어를 업데이트하기 위해 리포지토리에 액세스할 수 없습니다.
* * 추가 소프트웨어 *: BlueXP 분류를 설치하기 전에 호스트에 다음 소프트웨어를 설치해야 합니다.
+
** 사용 중인 OS에 따라 컨테이너 엔진 중 하나를 설치해야 합니다.
+
*** Docker Engine 버전 19.3.1 이상 https://docs.docker.com/engine/install/["설치 지침을 봅니다"^].
+
https://youtu.be/Ogoufel1q6c["이 비디오 시청"^] CentOS에 Docker를 설치하는 빠른 데모를 보려면

*** Podman 버전 4 이상 Podman을 설치하려면 시스템 패키지를 업데이트하십시오 (`sudo yum update -y`)를 클릭한 다음 Podman을 설치합니다 (`sudo yum install netavark -y`)를 클릭합니다.






* Python 버전 3.6 이상. https://www.python.org/downloads/["설치 지침을 봅니다"^].
+
** * NTP 고려 사항 *: NetApp에서는 NTP(네트워크 시간 프로토콜) 서비스를 사용하도록 BlueXP 분류 시스템을 구성할 것을 권장합니다. BlueXP 분류 시스템과 BlueXP Connector 시스템 간에 시간을 동기화해야 합니다.
** * Firewalld 고려 사항 *: 사용하려는 경우 `firewalld`BlueXP 분류를 설치하기 전에 활성화하는 것이 좋습니다. 다음 명령을 실행하여 구성합니다 `firewalld` 따라서 BlueXP 분류와 호환됩니다.
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
추가 BlueXP 분류 호스트를 스캐너 노드(분산 모델)로 사용할 계획이라면 이 규칙을 주 시스템에 추가하십시오.

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
Docker 또는 Podman을 활성화 또는 업데이트할 때마다 다시 시작해야 합니다 `firewalld` 설정.







== BlueXP 분류에서 아웃바운드 인터넷 액세스를 활성화합니다

BlueXP 분류에는 아웃바운드 인터넷 액세스가 필요합니다. 가상 또는 물리적 네트워크에서 인터넷 액세스에 프록시 서버를 사용하는 경우 BlueXP 분류 인스턴스에 다음 엔드포인트에 연결할 수 있는 아웃바운드 인터넷 액세스 권한이 있는지 확인합니다.


TIP: 인터넷에 연결되지 않은 사이트에 설치된 호스트 시스템에는 이 섹션이 필요하지 않습니다.

[cols="43,57"]
|===
| 엔드포인트 | 목적 


| https://api.bluexp.netapp.com 으로 문의하십시오 | NetApp 계정을 포함한 BlueXP 서비스와 통신합니다. 


| https://netapp-cloud-account.auth0.com \https://auth0.com 으로 문의하십시오 | BlueXP 웹 사이트와 통신하여 중앙 집중식 사용자 인증. 


| https://support.compliance.api.bluexp.netapp.com/\https://hub.docker.com\https://auth.docker.io\https://registry-1.docker.io\https://index.docker.io/\https://dseasb33srnrn.cloudfront.net/\https://production.cloudflare.docker.com/ | 소프트웨어 이미지, 매니페스트, 템플릿에 액세스하고 로그 및 메트릭을 보낼 수 있습니다. 


| https://support.compliance.api.bluexp.netapp.com/ 으로 문의하십시오 | NetApp에서 감사 레코드의 데이터를 스트리밍할 수 있습니다. 


| https://github.com/docker \https://download.docker.com 으로 문의하십시오 | Docker 설치를 위한 사전 필수 패키지를 제공합니다. 


| http://mirror.centos.org \http://mirrorlist.centos.org \http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm 를 참조하십시오 | CentOS 설치를 위한 필수 패키지를 제공합니다. 


| \http://packages.ubuntu.com/
\http://archive.ubuntu.com | Ubuntu 설치를 위한 필수 패키지를 제공합니다. 
|===


== 필요한 모든 포트가 활성화되어 있는지 확인합니다

커넥터, BlueXP 분류, Active Directory 및 데이터 소스 간의 통신에 필요한 모든 포트가 열려 있는지 확인해야 합니다.

[cols="25,25,50"]
|===
| 연결 유형 | 포트 | 설명 


| 커넥터 <>BlueXP 분류 | 8080(TCP), 443(TCP) 및 80 | Connector의 방화벽 또는 라우팅 규칙은 포트 443을 통해 BlueXP 분류 인스턴스 간에 인바운드 및 아웃바운드 트래픽을 허용해야 합니다. 포트 8080이 열려 있는지 확인하여 BlueXP에서 설치 진행률을 확인합니다. 


| 커넥터 <>ONTAP 클러스터(NAS) | 443(TCP)  a| 
BlueXP는 HTTPS를 사용하여 ONTAP 클러스터를 검색합니다. 사용자 지정 방화벽 정책을 사용하는 경우 커넥터 호스트는 포트 443을 통한 아웃바운드 HTTPS 액세스를 허용해야 합니다. Connector가 클라우드에 있는 경우 모든 아웃바운드 통신은 사전 정의된 방화벽 또는 라우팅 규칙으로 허용됩니다.

|===


== BlueXP 분류 필수 구성 요소 스크립트를 실행합니다

다음 단계에 따라 BlueXP 분류 전제 조건 스크립트를 실행합니다.

https://youtu.be/_RCYpuLXiV0?si=QLGUw8mqPrz9qs4B["이 비디오 시청"^] 필수 구성 요소 스크립트를 실행하고 결과를 해석하는 방법을 확인합니다.

.필요한 것
* Linux 시스템이 를 충족하는지 확인합니다 <<호스트 요구 사항을 확인합니다,호스트 요구 사항>>.
* 시스템에 2개의 필수 소프트웨어 패키지(Docker Engine 또는 Podman 및 Python 3)가 설치되어 있는지 확인합니다.
* Linux 시스템에 대한 루트 권한이 있는지 확인합니다.


.단계
. 에서 BlueXP 분류 필수 구성 요소 스크립트를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["NetApp Support 사이트"^]. 선택해야 하는 파일의 이름은 * standalone-pre-requised-tester-<version> * 입니다.
. 사용할 Linux 호스트에 파일을 복사합니다(사용) `scp` 또는 다른 방법 참조).
. 스크립트를 실행할 권한을 할당합니다.
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. 다음 명령을 사용하여 스크립트를 실행합니다.
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
인터넷 액세스가 없는 호스트에서 스크립트를 실행하는 경우에만 "--car사이트" 옵션을 추가합니다. 호스트가 인터넷에 연결되어 있지 않으면 특정 필수 구성 요소 테스트를 건너뜁니다.

. 이 스크립트는 BlueXP 분류 호스트 시스템의 IP 주소를 묻는 메시지를 표시합니다.
+
** IP 주소 또는 호스트 이름을 입력합니다.


. 이 스크립트에는 BlueXP Connector가 설치되어 있는지 여부를 묻는 메시지가 표시됩니다.
+
** 커넥터가 설치되어 있지 않으면 * N * 을 입력하십시오.
** 커넥터가 설치된 경우 * Y * 를 입력합니다. 그런 다음 테스트 스크립트가 이 연결을 테스트할 수 있도록 BlueXP Connector의 IP 주소 또는 호스트 이름을 입력합니다.


. 이 스크립트는 시스템에서 다양한 테스트를 실행하고 진행되면서 결과를 표시합니다. 작업이 완료되면 세션 로그를 라는 파일에 씁니다 `prerequisites-test-<timestamp>.log` 디렉토리에 있습니다 `/opt/netapp/install_logs`.


.결과
모든 필수 구성 요소 테스트가 성공적으로 실행된 경우 준비가 되면 호스트에 BlueXP 분류를 설치할 수 있습니다.

발견된 문제가 있는 경우 "권장" 또는 "필수"로 분류하여 해결합니다. 권장 문제는 일반적으로 BlueXP 분류 검사 및 분류 작업의 실행 속도를 느리게 만드는 항목입니다. 이러한 항목은 수정할 필요가 없지만, 이를 해결할 수 있습니다.

"필수" 문제가 있는 경우 문제를 해결하고 사전 요구 사항 테스트 스크립트를 다시 실행해야 합니다.
