---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: 클라우드 데이터 센스의 새로운 기능에 대해 알아보십시오. 
---
= 클라우드 데이터 센스의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클라우드 데이터 센스의 새로운 기능에 대해 알아보십시오.



== 2023년 4월 3일(버전 1.22)



=== 새로운 데이터 검색 평가 보고서

데이터 검색 평가 보고서는 스캔한 환경에 대한 상위 수준의 분석을 통해 시스템의 결과를 강조하고 문제 영역 및 잠재적인 개선 단계를 보여줍니다. 이 보고서의 목표는 데이터 거버넌스 문제, 데이터 보안 노출 및 데이터 세트의 데이터 규정 준수 공백에 대한 인식을 높이는 것입니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-discovery-assessment-report["데이터 검색 평가 보고서를 생성하고 사용하는 방법을 확인하십시오"].



=== 클라우드의 더 작은 인스턴스에 데이터 센스를 구축할 수 있습니다

AWS 환경의 BlueXP Connector에서 데이터 센스를 배포할 때 이제 기본 인스턴스에서 사용할 수 있는 것보다 작은 두 가지 인스턴스 유형 중에서 선택할 수 있습니다. 소규모 환경을 스캔하면 클라우드 비용을 절감할 수 있습니다. 그러나 더 작은 인스턴스를 사용할 때는 몇 가지 제한 사항이 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html#using-a-smaller-instance-type["사용 가능한 인스턴스 유형 및 제한 사항을 참조하십시오"].



=== 이제 독립 실행형 스크립트를 사용하여 Linux 시스템이 Data Sense를 설치할 수 있는지 테스트할 수 있습니다

Data Sense 설치를 실행하는 것과 관계없이 Linux 시스템이 모든 필수 구성 요소를 충족하는지 확인하려면 사전 요구 사항에 대한 테스트만 다운로드할 수 있는 별도의 스크립트가 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-test-linux-system.html["Linux 호스트가 Data Sense를 설치할 준비가 되었는지 확인하는 방법을 확인하십시오"].



=== 이제 Data Sense BYOL 라이센스가 다크 사이트에서 지원됩니다

이제 Data Sense BYOL 라이센스를 다크 사이트의 Digital Wallet에 업로드하여 라이센스가 낮아지면 알림을 받을 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-licensing-datasense.html#obtain-your-cloud-data-sense-license-file["Data Sense BYOL 라이센스를 획득하고 업로드하는 방법을 알아보십시오"].



== 2023년 3월 7일(버전 1.21)



=== 데이터 감지 UI에서 사용자 지정 범주를 추가하는 새로운 기능입니다

이제 Data Sense를 사용하여 사용자 지정 범주를 추가할 수 있으므로 데이터 센스에서 해당 범주에 적합한 파일을 식별할 수 있습니다. 데이터 센스의 기능이 매우 많습니다 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-categories["미리 정의된 범주"]따라서 이 기능을 사용하면 사용자 지정 범주를 추가하여 조직에서 고유한 정보를 데이터에서 찾을 위치를 식별할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-categories["자세한 정보"^].



=== 이제 데이터 감지 UI에서 사용자 지정 키워드를 추가할 수 있습니다

Data Sense는 데이터 센스에서 잠시 동안 향후 검색할 때 식별할 수 있는 맞춤형 키워드를 추가할 수 있습니다. 그러나 Data Sense Linux 호스트에 로그인하고 명령줄 인터페이스를 사용하여 키워드를 추가해야 합니다. 이 릴리즈에서는 데이터 감지 UI에서 사용자 지정 키워드를 추가하는 기능이 있으므로 이러한 키워드를 쉽게 추가하고 편집할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["데이터 감지 UI에서 사용자 지정 키워드를 추가하는 방법에 대해 자세히 알아보십시오"^].



=== "마지막 액세스 시간"이 변경될 때 데이터 감지 * 가 * 스캔 파일을 하지 * 수 있는 기능

기본적으로 데이터 센스에 적절한 "쓰기" 권한이 없으면 데이터 센스에서 "마지막 액세스 시간"을 원래 타임 스탬프로 되돌릴 수 없기 때문에 시스템이 볼륨의 파일을 검색하지 않습니다. 그러나 마지막 액세스 시간이 파일의 원래 시간으로 재설정되는 것을 염려하지 않을 경우, 데이터 센스에서 권한에 관계없이 볼륨을 스캔하도록 구성 페이지에서 이 동작을 재정의할 수 있습니다.

이 기능과 함께 "Scan Analysis Event(스캔 분석 이벤트)"라는 새 필터가 추가되어 데이터 센스에서 마지막 액세스 시간을 되돌릴 수 없어 분류되지 않은 파일이나 Data Sense가 마지막으로 액세스한 시간을 되돌릴 수 없는 경우에도 분류된 파일을 볼 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-collected-metadata.html#last-access-time-timestamp[""마지막 액세스 시간 타임스탬프" 및 데이터 센스에 필요한 권한에 대해 자세히 알아보십시오"].



=== 세 가지 새로운 유형의 개인 데이터는 데이터 센스로 식별됩니다

데이터 센스를 사용하면 다음 유형의 데이터가 포함된 파일을 식별하고 분류할 수 있습니다.

* 보츠와나 ID 카드(오만) 번호
* 보츠와나 여권 번호
* 싱가포르 국가 등록 ID 카드(NRIC)


https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["데이터 센스에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하십시오"].



=== 디렉토리의 기능이 업데이트되었습니다

* 이제 데이터 조사 보고서에 대한 "Light CSV Report(라이트 CSV 보고서)" 옵션에 디렉토리의 정보가 포함됩니다.
* 이제 "마지막 액세스" 시간 필터에 파일과 디렉터리 모두의 마지막 액세스 시간이 표시됩니다.




=== 설치 개선 사항

* Data Sense는 CentOS Stream 8을 실행하는 Linux 호스트에 설치할 수 있습니다.
* 이제 인터넷에 연결되지 않은 사이트(다크 사이트)용 Data Sense 설치 프로그램이 사전 검사를 수행하여 시스템 및 네트워킹 요구 사항이 제대로 설치되었는지 확인합니다.
* 설치 감사 로그 파일은 지금 저장되며 에 기록됩니다 `/ops/netapp/install_logs`.




== 2023년 2월 5일(버전 1.20)



=== 모든 이메일 주소로 정책 기반 알림 이메일을 보낼 수 있습니다

이전 버전의 Cloud Data Sense에서는 특정 중요 정책이 결과를 반환할 때 계정의 BlueXP 사용자에게 전자 메일 알림을 보낼 수 있습니다. 이 기능을 사용하면 온라인 상태가 아닐 때 데이터를 보호하기 위한 알림을 받을 수 있습니다. 이제 BlueXP 계정에 없는 다른 모든 사용자(최대 20개의 이메일 주소)에게 정책의 이메일 알림을 보낼 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["정책 결과를 기반으로 이메일 알림을 보내는 방법에 대해 자세히 알아보십시오"].



=== 이제 데이터 감지 UI에서 개인 패턴을 추가할 수 있습니다

Data Sense는 데이터 센스에서 잠시 후 검사할 때 식별할 수 있는 사용자 지정 "개인 데이터"를 추가할 수 있는 기능을 가지고 있습니다. 그러나 Data Sense Linux 호스트에 로그인하고 명령줄을 사용하여 사용자 지정 패턴을 추가해야 합니다. 이 릴리즈에서는 regex를 사용하여 개인 패턴을 추가하는 기능이 Data Sense UI에 포함되어 있으므로 이러한 사용자 지정 패턴을 매우 쉽게 추가하고 편집할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["데이터 감지 UI에서 사용자 지정 패턴을 추가하는 방법에 대해 자세히 알아보십시오"^].



=== 데이터 센스를 사용하여 1,500만 개의 파일을 이동할 수 있습니다

과거에는 Data Sense를 통해 최대 100,000개의 소스 파일을 모든 NFS 공유로 이동할 수 있었습니다. 이제 한 번에 최대 1,500만 개의 파일을 이동할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["데이터 센스를 사용하여 소스 파일을 이동하는 방법에 대해 자세히 알아보십시오"].



=== SharePoint Online 파일에 액세스할 수 있는 사용자 수를 볼 수 있습니다

"액세스 권한이 있는 사용자 수" 필터는 이제 SharePoint Online 리포지토리에 저장된 파일을 지원합니다. 이전에는 CIFS 공유의 파일만 지원되었습니다. Active Directory 기반이 아닌 SharePoint 그룹은 현재 이 필터에서 계산되지 않습니다.



=== 새 "부분 성공" 상태가 작업 상태 패널에 추가되었습니다

새로운 "부분 성공" 상태는 데이터 감지 작업이 완료되었고 일부 항목이 실패했으며, 예를 들어 100개의 파일을 이동하거나 삭제할 때 일부 항목이 성공했음을 나타냅니다. 또한 "완료됨" 상태의 이름이 "성공"으로 변경되었습니다. 과거에는 "완료" 상태에 성공했고 실패한 작업이 나열될 수 있습니다. 이제 "성공" 상태는 모든 작업이 모든 항목에 성공했음을 의미합니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-view-compliance-actions.html["작업 상태 패널을 보는 방법을 참조하십시오"].



== 2023년 1월 9일(버전 1.19)



=== 중요한 데이터가 포함되어 있고 지나치게 허용적인 파일 차트를 볼 수 있는 기능

Governance 대시보드에는 중요한 데이터(민감한 개인 데이터 및 민감한 개인 데이터 포함)를 포함하고 지나치게 허용적인 파일의 열 지도를 제공하는 새로운 _Sensitive Data 및 Wide Permissions_영역이 추가되었습니다. 이렇게 하면 민감한 데이터와 관련하여 어떤 위험이 있을 수 있는지 확인할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["자세한 정보"].



=== 데이터 조사 페이지에서 3개의 새 필터를 사용할 수 있습니다

새 필터를 사용하여 데이터 조사 페이지에 표시되는 결과를 구체화할 수 있습니다.

* "액세스 권한이 있는 사용자 수" 필터는 특정 수의 사용자에게 열려 있는 파일과 폴더를 표시합니다. 숫자 범위를 선택하여 결과를 구체화할 수 있습니다. 예를 들어 51-100명의 사용자가 액세스할 수 있는 파일을 확인할 수 있습니다.
* 이제 "Created Time(생성 시간)", "Discovered Time(검색 시간)", "Last Modified(마지막 수정)" 및 "Last Accessed(마지막 액세스)" 필터를 사용하여 미리 정의된 날짜 범위를 선택하는 대신 사용자 지정 날짜 범위를 만들 수 있습니다. 예를 들어 "만든 시간", "6개월 이전" 또는 "최근 10일" 내의 "마지막으로 수정한 날짜"가 있는 파일을 찾을 수 있습니다.
* 이제 "파일 경로" 필터를 사용하여 필터링된 쿼리 결과에서 제외할 경로를 지정할 수 있습니다. 특정 데이터를 포함 및 제외하기 위한 경로를 입력하면 데이터 센스에서 포함된 경로의 모든 파일을 먼저 찾은 다음 제외된 경로에서 파일을 제거한 다음 결과를 표시합니다.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-investigate-data.html#filtering-data-in-the-data-investigation-page["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하십시오"].



=== 데이터 센스에서 일본 개인 번호를 식별할 수 있습니다

데이터 센스에서 일본어 개인 번호(내 번호라고도 함)가 포함된 파일을 식별하고 분류할 수 있습니다. 여기에는 개인 및 회사 내 번호가 모두 포함됩니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["데이터 센스에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하십시오"].



== 2022년 12월 11일(버전 1.18)



=== 사내 설치 기능의 향상

사내 Data Sense 설치를 위해 다음과 같은 개선 사항이 추가되었습니다.

* 이제 사내 호스트에서 설치를 시작하기 전에 몇 가지 추가 사전 요구 사항을 확인합니다. 이렇게 하면 호스트 시스템이 데이터 감지 소프트웨어를 설치할 준비가 100% 되어 있는지 확인할 수 있습니다.
+
** 에 충분한 공간이 있는지 테스트합니다 `/var/lib/docker`, `/tmp`, 및 `/opt`
** 필요한 모든 폴더에 대한 관련 권한을 테스트합니다


* 구성 페이지에서 작업 환경 섹션에 이제 _Working Environment ID_ 및 _Scanner Group_이름이 표시됩니다. 데이터 소스를 스캔하기 위해 추가 처리 성능을 제공하기 위해 여러 데이터 감지 호스트를 사용하려는 경우 작업 환경 ID를 알아야 합니다.
* 또한 구성 페이지에서 새 섹션에는 설정한 스캐너 그룹과 각 그룹에 있는 스캐너 노드가 표시됩니다.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html["단일 호스트 서버 및 여러 호스트에 Data Sense를 설치하는 방법에 대해 자세히 알아보십시오"].



== 2022년 11월 13일(버전 1.17)



=== SharePoint 온-프레미스 계정 스캔 지원

이제 데이터 센스를 통해 SharePoint Online 계정과 SharePoint 온-프레미스 계정(SharePoint Server)을 모두 검색할 수 있습니다. 자체 서버에 SharePoint를 설치하거나 인터넷에 액세스할 수 없는 사이트에 SharePoint를 설치해야 하는 경우 이제 데이터 센스에서 해당 계정의 사용자 파일을 검색할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["자세한 정보"^].



=== 여러 디렉토리(폴더 또는 공유)를 재검색하는 기능

이제 변경 사항이 시스템에 반영되도록 여러 디렉토리(폴더 또는 공유)를 즉시 재검색할 수 있습니다. 이렇게 하면 특정 데이터를 다른 데이터보다 먼저 다시 검색하게 할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["디렉토리를 다시 검색하는 방법을 참조하십시오"^].



=== 특정 데이터 소스를 스캔하기 위해 사내 "스캐너" 노드를 추가하는 기능

온-프레미스 위치에 데이터 센스를 설치한 경우 특정 데이터 원본을 스캔하기 위해 스캔 처리 성능이 더 필요한 경우 "스캐너" 노드를 더 추가하고 해당 데이터 원본을 스캔하도록 할당할 수 있습니다. 관리자 노드를 설치한 직후 스캐너 노드를 추가하거나 나중에 스캐너 노드를 추가할 수 있습니다.

필요한 경우 스캔 중인 데이터 소스에 물리적으로 가까운 호스트 시스템에 스캐너 노드를 설치할 수 있습니다. 스캐너 노드가 데이터에 가까울수록 데이터 스캔 시 네트워크 대기 시간이 최대한 줄어들기 때문에 성능이 향상됩니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["스캐너 노드를 설치하여 추가 데이터 원본을 스캔하는 방법을 알아봅니다"^].



=== 이제 온-프레미스 설치 관리자가 설치를 시작하기 전에 사전 검사를 수행합니다

Linux 시스템에 Data Sense를 설치할 때 설치 관리자는 실제 설치를 시작하기 전에 시스템이 필요한 모든 요구 사항(CPU, RAM, 용량, 네트워킹 등)을 충족하는지 확인합니다. 따라서 * 설치에 시간을 소비하기 전에 * 문제를 파악할 수 있습니다.



== 2022년 9월 6일(버전 1.16)



=== 파일의 변경 사항을 반영하기 위해 저장소를 즉시 다시 검색할 수 있습니다

변경 내용이 시스템에 반영되도록 특정 리포지토리를 즉시 다시 스캔해야 하는 경우 리포지토리를 선택하고 다시 검색할 수 있습니다. 이렇게 하면 특정 데이터를 다른 데이터보다 먼저 다시 검색하게 할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["디렉토리를 다시 검색하는 방법을 참조하십시오"^].



=== 데이터 조사 페이지의 데이터 감지 스캔 상태에 대한 새 필터

“Analysis Status(분석 상태)” 필터를 사용하면 데이터 감지 스캔의 특정 단계에 있는 파일을 나열할 수 있습니다. 옵션을 선택하여 * 첫 번째 스캔 보류 *, * 완료됨 * 스캔 중, * 재스캔 보류 * 또는 * 실패 * 가 스캔되는 파일 목록을 표시할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하십시오"^].



=== 데이터 주제는 이제 스캔에서 발견된 "개인 데이터"의 일부로 간주됩니다

이제 Data Sense는 규정 준수 대시보드에 표시되는 개인 결과의 일부로 데이터 주제를 인식합니다. 또한 조사 페이지에서 검색을 수행할 때 "개인 데이터"에서 "데이터 제목"을 선택하여 데이터 주제가 포함된 파일만 볼 수 있습니다.



=== 이제 데이터 감지 이동 경로 파일은 검색에서 "범주"의 일부로 간주됩니다

이제 Data Sense는 Breadcrumb 파일을 Compliance Dashboard에 나타나는 범주의 일부로 인식합니다. 소스 위치에서 NFS 공유로 파일을 이동할 때 데이터 센스에서 생성되는 파일입니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Breadcrumb 파일을 만드는 방법에 대해 자세히 알아보십시오"^].

또한 조사 페이지에서 검색을 수행할 때 "범주" 아래의 "데이터 감지 브레드크럼"을 선택하여 데이터 감지 브레드크럼 파일만 볼 수 있습니다.



== 2022년 8월 7일(버전 1.15)



=== 뉴질랜드의 5가지 새로운 유형의 개인 데이터는 데이터 센스로 식별됩니다

데이터 센스를 사용하면 다음 유형의 데이터가 포함된 파일을 식별하고 분류할 수 있습니다.

* 뉴질랜드 은행 계좌 번호
* 뉴질랜드 운전면허증 번호
* 뉴질랜드 IRD 번호(세금 ID)
* 뉴질랜드 NHI(National Health Index) 번호
* 뉴질랜드 여권 번호


link:reference-private-data-categories.html#types-of-personal-data["데이터 센스에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하십시오"].



=== 파일이 이동된 이유를 나타내기 위해 Breadcrumb 파일을 추가하는 기능입니다

데이터 감지 기능을 사용하여 소스 파일을 NFS 공유로 이동할 때 이제 이동 파일 위치에 이동 경로 파일을 그대로 둘 수 있습니다. Breadcrumb 파일을 사용하면 파일이 원래 위치에서 이동된 이유를 쉽게 이해할 수 있습니다. 이동된 각 파일에 대해 시스템은 "<filename>-breadcrumb-<date>.txt"라는 소스 위치에 Breadcrumb 파일을 만들어 파일이 이동된 위치와 파일을 이동한 사용자를 표시합니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["자세한 정보"^].



=== 디렉터리에 있는 개인 데이터 및 중요한 개인 데이터는 조사 결과에 표시됩니다

이제 데이터 조사 페이지에는 디렉토리(폴더 및 공유) 내에서 찾은 개인 데이터 및 중요한 개인 데이터에 대한 결과가 표시됩니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-files-that-contain-personal-data["여기 예를 참조하십시오"^].



=== 성공적으로 분류한 볼륨, 버킷 등의 상태를 봅니다

Data Sense가 스캔(볼륨, 버킷 등)하는 개별 리포지토리를 볼 때 "매핑" 수와 "분류" 수를 확인할 수 있습니다. 모든 데이터에 대해 전체 AI ID가 수행되므로 분류에 시간이 더 오래 걸립니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["이 정보를 보는 방법을 참조하십시오"^].



=== 이제 데이터 센스에서 식별할 수 있는 사용자 지정 패턴을 데이터에 추가할 수 있습니다

데이터 센스에서 향후 검색에서 식별할 수 있는 사용자 지정 "개인 데이터"를 추가하는 방법은 두 가지가 있습니다. 이렇게 하면 중요한 데이터가 조직의 모든 파일에 있는 위치를 전체적으로 파악할 수 있습니다.

* 텍스트 파일에서 사용자 지정 키워드를 추가할 수 있습니다.
* 정규식(regex)을 사용하여 개인 패턴을 추가할 수 있습니다.


이러한 키워드 및 패턴은 데이터 센스에서 이미 사용하는 기존의 미리 정의된 패턴에 추가되며, 결과는 개인 패턴 섹션 아래에 표시됩니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html["자세한 정보"^].



== 2022년 7월 6일(버전 1.14)



=== 이제 디렉터리에 액세스할 수 있는 사용자 및 그룹을 볼 수 있습니다

과거에는 개별 파일에 허용된 열린 권한의 유형을 볼 수 있었습니다. 이제 디렉토리(폴더 및 파일 공유)에 대한 액세스 권한이 있는 모든 사용자 또는 그룹의 목록과 해당 사용자 권한 유형을 볼 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["폴더 및 파일 공유에 대한 액세스 권한이 있는 사용자 및 그룹을 보는 방법에 대해 알아봅니다"].



=== 리포지토리 스캔을 "일시 중지"하여 특정 콘텐츠 스캔을 일시적으로 중지할 수 있습니다

스캐닝을 일시 중지하면 데이터 센스에서 볼륨 또는 버킷에 대한 추가 또는 변경 사항에 대해 향후 스캐닝을 수행하지 않지만 시스템에서 현재 모든 결과를 계속 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["스캔을 일시 중지하고 다시 시작하는 방법을 참조하십시오"].



=== 세 가지 추가 상태에서 미국 운전면허증 데이터를 데이터 센스로 식별할 수 있습니다

데이터 센스는 인디애나, 뉴욕 및 텍사스의 드라이버 라이센스 데이터가 포함된 파일을 식별하고 분류할 수 있습니다. link:reference-private-data-categories.html#types-of-personal-data["데이터 센스에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하십시오"].



=== 이제 정책은 검색 기준과 일치하는 디렉토리를 반환합니다

과거에는 사용자 지정 정책을 만들었을 때 검색 기준과 일치하는 파일이 결과에 표시됩니다. 이제 결과에 쿼리와 일치하는 디렉토리(폴더 및 파일 공유)도 표시됩니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies["정책 생성에 대해 자세히 알아보십시오"].



=== 이제 데이터 센스를 통해 한 번에 최대 100,000개의 파일을 이동할 수 있습니다

Data Sense를 사용하여 스캔한 데이터 소스에서 NFS 공유로 파일을 이동하려는 경우 최대 파일 수가 100,000개로 늘어났습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["데이터 센스를 사용하여 파일을 이동하는 방법을 확인하십시오"].



== 2022년 6월 12일(버전 1.13.1)



=== 이제 데이터 조사 페이지에서 결과를 .JSON 보고서로 다운로드할 수 있습니다

데이터 조사 페이지에서 데이터를 필터링한 후에는 데이터를 .JSON 파일에 보고서로 저장하여 NFS 공유로 내보낼 수 있으며 로컬 시스템의 .csv 파일에 데이터를 저장할 수도 있습니다. 데이터 센스에 내보내기 액세스에 대한 올바른 권한이 있는지 확인하십시오. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report["데이터 조사 페이지에서 보고서를 만드는 방법을 알아봅니다"].



=== Data Sense UI에서 Data Sense를 제거할 수 있습니다

Data Sense를 제거하여 호스트에서 소프트웨어를 영구적으로 제거할 수 있으며, 클라우드 배포의 경우 Data Sense가 배포된 가상 머신/인스턴스를 삭제할 수 있습니다. 인스턴스를 삭제하면 데이터 센스에서 스캔한 모든 인덱싱된 정보가 영구적으로 삭제됩니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html["방법을 확인하십시오"].



=== 이제 감사 로깅을 사용하여 Data Sense가 수행한 작업 기록을 추적할 수 있습니다

감사 로그는 Data Sense가 검색 중인 모든 작업 환경 및 데이터 소스의 파일에 대해 Data Sense가 수행한 관리 활동을 추적합니다. 작업은 사용자 생성(파일 삭제, 정책 생성 등) 또는 생성된 정책(파일에 레이블 자동 추가, 파일 자동 삭제 등)이 될 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html["감사 로그에 대한 자세한 내용은 을 참조하십시오"].



=== 데이터 조사 페이지의 중요 ID 수에 대한 새 필터

“Number of identifier(식별자 수)” 필터를 사용하면 개인 데이터와 민감한 개인 데이터를 포함하여 특정 수의 중요한 식별자가 있는 파일을 나열할 수 있습니다. 1-10 또는 501-1000과 같은 범위를 선택하여 해당 수의 중요한 식별자가 포함된 파일만 볼 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하십시오"].



=== 이제 작성한 기존 정책을 편집할 수 있습니다

이전에 만든 사용자 지정 정책을 변경해야 하는 경우 새 정책을 만드는 대신 정책을 편집할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies["정책을 편집하는 방법을 알아봅니다"].



== 2022년 5월 11일(버전 1.12.1)



=== Google Drive 계정의 데이터 스캔에 대한 지원이 추가되었습니다

이제 Google Drive 계정을 데이터 센스에 추가하여 해당 Google Drive 계정의 문서와 파일을 검색할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html["Google Drive 계정을 검색하는 방법을 확인하십시오"].

Data Sense는 다음 Google Docs 제품군(문서, 시트 및 슬라이드)에서 개인 식별 정보(PII)를 식별할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files["기존 파일 형식"].



=== 데이터 조사 페이지에 디렉토리 수준 보기가 추가되었습니다

이제 모든 파일과 데이터베이스의 데이터를 보고 필터링할 수 있을 뿐 아니라 데이터 조사 페이지의 폴더 및 공유 내의 모든 데이터를 기반으로 데이터를 보고 필터링할 수 있습니다. 디렉토리는 스캔된 CIFS 및 NFS 공유와 OneDrive, SharePoint 및 Google Drive 폴더에 대해 인덱싱됩니다. 따라서 이제 디렉토리 수준에서 사용 권한을 보고 데이터를 관리할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["스캔한 데이터의 디렉터리 보기를 선택하는 방법을 알아봅니다"].



=== 그룹 을 확장하여 파일 액세스 권한이 있는 사용자/구성원을 표시합니다

이제 데이터 감지 사용 권한 기능의 일부로 파일에 액세스할 수 있는 사용자 및 그룹 목록을 볼 수 있습니다. 각 그룹을 확장하여 그룹의 사용자 목록을 표시할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files["파일에 대한 읽기 및/또는 쓰기 권한이 있는 사용자 및 그룹을 보는 방법에 대해 알아봅니다"].



=== 데이터 조사 페이지에 두 개의 새 필터가 추가되었습니다

* “디렉터리 유형” 필터를 사용하면 폴더 또는 공유만 볼 수 있도록 데이터를 구체화할 수 있습니다. 결과는 새 * 디렉터리 * 탭에 표시됩니다.
* "사용자/그룹 권한" 필터를 사용하면 특정 사용자 또는 그룹에 읽기 및/또는 쓰기 권한이 있는 파일, 폴더 및 공유를 나열할 수 있습니다. 여러 사용자 및/또는 그룹 이름을 선택하거나 부분 이름을 입력할 수 있습니다.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하십시오"].



== 2022년 4월 5일(버전 1.11.1)



=== 네 가지 새로운 유형의 호주 개인 데이터는 데이터 센스로 식별할 수 있습니다

데이터 센스를 사용하면 오스트레일리아 TFN(세금 파일 번호), 오스트레일리아 운전면허증 번호, 오스트레일리아 의료보험 번호 및 호주 여권 번호가 포함된 파일을 식별하고 분류할 수 있습니다. link:reference-private-data-categories.html#types-of-personal-data["데이터 센스에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하십시오"].



=== 이제 글로벌 Active Directory 서버가 LDAP 서버가 될 수 있습니다

Data Sense와 통합하는 글로벌 Active Directory 서버는 이제 이전에 지원되는 DNS 서버 외에도 LDAP 서버가 될 수 있습니다. link:task-add-active-directory-datasense.html["자세한 내용을 보려면 여기를 클릭하십시오"].



== 2022년 3월 15일(버전 1.10.0)



=== 새 필터 - 특정 사용자 또는 그룹에 읽기 또는 쓰기 권한이 있는 파일을 표시합니다

"사용자/그룹 권한"이라는 새 필터가 추가되어 특정 사용자 또는 그룹에 읽기 및/또는 쓰기 권한이 있는 파일을 나열할 수 있습니다. 하나 이상의 사용자 및/또는 그룹 이름을 선택하거나 부분 이름을 입력할 수 있습니다. 이 기능은 Cloud Volumes ONTAP, 온프레미스 ONTAP, Azure NetApp Files, ONTAP용 Amazon FSx 및 파일 공유의 볼륨에 사용할 수 있습니다.



=== Data Sense는 SharePoint 및 OneDrive 계정의 파일에 대한 사용 권한을 결정할 수 있습니다

Data Sense는 지금 OneDrive 계정 및 SharePoint 계정에서 스캔되는 파일에 대한 사용 권한을 읽을 수 있습니다. 이 정보는 파일에 대한 조사 창 세부 정보와 거버넌스 대시보드의 열기 권한 영역에 표시됩니다.



=== 데이터 센스로 두 가지 유형의 개인 데이터를 추가로 식별할 수 있습니다

* 프랑스어 INSEE - INSEE 코드는 프랑스 통계 및 경제 연구(INSEE)에서 다양한 엔터티를 식별하기 위해 사용하는 숫자 코드입니다.
* 암호 - 이 정보는 영숫자 문자열 옆에 있는 "password"라는 단어의 변이를 찾아 근접 유효성 검사를 통해 식별됩니다. 찾은 항목 수는 규정 준수 대시보드의 "개인 결과" 아래에 나열됩니다. 검색 창에서 Filter * Personal Data > Password * 를 사용하여 암호가 포함된 파일을 검색할 수 있습니다.




=== 어두운 사이트에 배포할 때 OneDrive 및 SharePoint 데이터 스캔 지원

인터넷에 액세스할 수 없는 온프레미스 사이트의 호스트에 Cloud Data Sense를 배포했다면 이제 OneDrive 계정 또는 SharePoint 계정에서 로컬 데이터를 검색할 수 있습니다. link:task-deploy-compliance-dark-site.html#sharepoint-and-onedrive-special-requirements["다음 끝점에 대한 액세스를 허용해야 합니다."]



=== Cloud Data Sense를 사용하여 Cloud Backup 파일을 검사하는 베타 기능은 이 릴리즈에서 더 이상 제공되지 않습니다



== 2022년 2월 9일



=== Microsoft SharePoint 온라인 계정 검색에 대한 지원이 추가되었습니다

이제 SharePoint 사이트의 문서 및 파일을 스캔하기 위해 SharePoint 온라인 계정을 데이터 센스에 추가할 수 있습니다. link:task-scanning-sharepoint.html["SharePoint 계정을 검색하는 방법을 알아봅니다"].



=== Data Sense는 데이터 소스에서 타겟 위치로 파일을 복사하고 이러한 파일을 동기화할 수 있습니다

이 기능은 데이터를 마이그레이션할 때 파일의 마지막 변경 내용을 확인하고자 하는 경우에 유용합니다. 이 작업은 를 사용합니다 https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["NetApp Cloud Sync를 참조하십시오"^] 소스에서 타겟으로 데이터를 복제 및 동기화하는 기능

link:task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["파일 복사 및 동기화 방법을 참조하십시오"].



=== SAR 보고서에 대한 새로운 언어 지원

DSAR(Data Subject Access Request) 보고서를 생성하기 위해 데이터 주체 이름을 검색할 때 독일어 및 스페인어가 지원됩니다. 이 보고서는 GDPR 또는 이와 유사한 데이터 개인 정보 보호 법률을 준수하기 위한 조직의 요구 사항을 돕기 위해 작성되었습니다.



=== 데이터 센스를 통해 세 가지 유형의 개인 데이터를 추가로 식별할 수 있습니다

이제 Data Sense는 파일에서 프랑스어 주민등록번호, 프랑스어 ID 및 프랑스어 드라이버 라이센스 번호를 찾을 수 있습니다. link:reference-private-data-categories.html#types-of-personal-data["스캔 시 데이터 센스에서 식별하는 모든 개인 데이터 유형 목록을 참조하십시오"].



=== 커넥터에 대한 데이터 감지 통신을 위해 보안 그룹 포트가 변경되었습니다

Cloud Manager Connector의 보안 그룹은 보안을 강화하기 위해 Data Sense 인스턴스에 대한 인바운드 및 아웃바운드 트래픽에 포트 80 대신 포트 443을 사용합니다. 두 포트 모두 현재 열려 있으므로 문제가 발생하지 않도록 해야 합니다. 하지만 포트 80은 향후 릴리스에서 더 이상 사용되지 않으므로 이전 버전의 Connector 배포에서 보안 그룹을 업데이트해야 합니다.
