---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: BlueXP 분류의 새로운 기능에 대해 알아보십시오. 
---
= BlueXP  분류의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 분류의 새로운 기능에 대해 알아보십시오.



== 2025년 8월 11일



=== 버전 1.46

이 BlueXP classification 릴리스에는 버그 수정과 다음 업데이트가 포함되어 있습니다.

.BlueXP 타임라인에서 향상된 스캔 이벤트 통찰력
이제 BlueXP 타임라인은 BlueXP classification 위한 스캔 이벤트에 대한 향상된 통찰력을 지원합니다.  이제 타임라인에는 작업 환경 스캔이 시작되는 시점, 작업 환경의 상태, 문제가 표시됩니다.  공유 및 작업 환경의 상태는 매핑 스캔에만 사용할 수 있습니다.

BlueXP 타임라인에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html["BlueXP 작업 모니터링"^] .

.RHEL 9.6 지원
이 릴리스에서는 다크 사이트 배포를 포함하여 BlueXP classification 의 수동 온프레미스 설치를 위한 Red Hat Enterprise Linux v9.6에 대한 지원이 추가되었습니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.



== 2025년 7월 14일



=== 버전 1.45

이 BlueXP classification 릴리스에는 리소스 활용도를 최적화하는 코드 변경 사항이 포함되어 있습니다.

.스캔을 위해 파일 공유를 추가하는 향상된 워크플로
파일 공유 그룹에 파일 공유를 추가하는 워크플로가 간소화되었습니다. 또한, 이제 인증 유형(Kerberos 또는 NTLM)에 따라 CIFS 프로토콜 지원이 차별화됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["파일 공유를 스캔합니다"]참조하십시오.

.향상된 파일 소유자 정보
이제 조사 탭에서 캡처된 파일의 파일 소유자에 대한 자세한 정보를 볼 수 있습니다. 조사 탭에서 파일의 메타데이터를 볼 때 파일 소유자를 찾은 다음 **세부 정보 보기**를 선택하면 사용자 이름, 이메일, SAM 계정 이름을 확인할 수 있습니다. 이 사용자가 소유한 다른 항목도 볼 수 있습니다. 이 기능은 Active Directory가 설치된 작업 환경에서만 사용할 수 있습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["조직에 저장된 데이터를 조사합니다"]참조하십시오.



== 2025년 6월 10일



=== 버전 1.44

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.거버넌스 대시보드의 업데이트 시간이 개선되었습니다.
거버넌스 대시보드의 개별 구성 요소에 대한 업데이트 시간이 개선되었습니다. 다음 표는 각 구성 요소의 업데이트 빈도를 보여줍니다.

[cols="1,1"]
|===
| 구성 요소 | 업데이트 시간 


| 데이터 사용 기간 | 24시간 


| 범주 | 24시간 


| 데이터 개요 | 5분 


| 중복 파일 | 2시간 


| 파일 형식 | 24시간 


| 비업무용 데이터 | 2시간 


| 사용 권한을 엽니다 | 24시간 


| 저장된 검색 | 2시간 


| 민감한 데이터 및 광범위한 권한 | 24시간 


| 데이터 크기 | 24시간 


| 오래된 데이터 | 2시간 


| 민감도 수준별 상위 데이터 저장소 | 2시간 
|===
마지막 업데이트 시간을 확인하고 중복 파일, 비업무용 데이터, 저장된 검색, 오래된 데이터, 민감도 수준별 상위 데이터 저장소 구성 요소를 수동으로 업데이트할 수 있습니다. 거버넌스 대시보드에 대한 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["조직에 저장된 데이터에 대한 거버넌스 세부 정보를 봅니다"] .

.성능 및 보안 개선
BlueXP 분류의 성능, 메모리 소비, 보안을 개선하기 위해 개선 사항이 적용되었습니다.

.버그 수정
Redis가 업그레이드되어 BlueXP 분류의 안정성이 향상되었습니다. BlueXP 분류는 이제 Elasticsearch를 사용하여 스캔 중 파일 개수 보고의 정확도를 높였습니다.



== 2025년 5월 12일



=== 버전 1.43

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.분류 스캔의 우선 순위를 지정합니다
BlueXP  분류는 매핑 전용 스캔뿐만 아니라 스캔 지도 및 분류 우선 순위를 지정할 수 있는 기능을 지원하므로 먼저 완료된 스캔을 선택할 수 있습니다. 맵 및 분류 스캔의 우선 순위는 스캔이 시작되는 동안과 그 전에 지원됩니다. 스캔이 진행 중일 때 스캔 우선 순위를 지정하도록 선택하면 매핑 및 분류 스캔이 모두 우선 순위가 지정됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"]참조하십시오.

.캐나다 PII(개인 식별 정보) 데이터 범주 지원
BlueXP  분류 스캔은 캐나다 PII 데이터 범주를 식별합니다. 이러한 범주에는 은행 정보, 여권 번호, 사회 보험 번호, 운전면허증 번호 및 모든 캐나다 주 및 영토에 대한 건강 카드 번호가 포함됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["개인 데이터 범주"]참조하십시오.

.사용자 지정 분류(미리 보기)
BlueXP  분류는 지도 및 분류 스캔에 대한 사용자 정의 분류를 지원합니다. 사용자 지정 분류를 사용하면 정규식을 사용하여 조직 고유의 데이터를 캡처하도록 BlueXP  스캔을 조정할 수 있습니다. 이 기능은 현재 미리보기 중입니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["사용자 지정 분류를 추가합니다"]참조하십시오.

.저장된 검색 탭
** Policies** 탭의 이름이 link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["** 저장된 검색**"]변경되었습니다. 기능은 변경되지 않았습니다.

.스캔 이벤트를 BlueXP  타임라인으로 보냅니다
BlueXP  분류는 에 분류 이벤트(스캔이 시작되었을 때 및 종료되었을 때)를 보낼 수 있도록 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  타임라인"^]지원합니다.

.보안 업데이트
* Keras 패키지가 업데이트되어 취약점을 완화합니다(BDSA-2025-0107 및 BDSA-2025-1984).
* Docker 컨테이너 구성이 업데이트되었습니다. 컨테이너는 더 이상 원시 네트워크 패킷을 만들기 위해 호스트의 네트워크 인터페이스에 액세스할 수 없습니다. 이 업데이트는 불필요한 액세스를 줄여 잠재적인 보안 위험을 완화합니다.


.성능 향상
RAM 사용을 줄이고 BlueXP  분류의 전반적인 성능을 개선하기 위해 코드 개선 사항이 구현되었습니다.

.버그 수정
StorageGRID 검사가 실패하고, 조사 페이지 필터 옵션이 로드되지 않으며, 대량 평가를 위해 다운로드되지 않는 데이터 검색 평가가 수정되었습니다.



== 2025년 4월 14일



=== 버전 1.42

이 BlueXP  분류 릴리스에는 다음이 포함됩니다.

.작업 환경을 위한 대량 스캔
BlueXP  분류는 작업 환경에 대한 대량 작업을 지원합니다. 스캔 매핑 활성화, 스캔 매핑 및 분류 활성화, 스캔 비활성화 또는 작업 환경의 볼륨에 대한 사용자 정의 구성 생성을 선택할 수 있습니다. 개별 볼륨에 대해 선택하면 대량 선택이 무시됩니다. 대량 작업을 수행하려면 ** 구성** 페이지로 이동하여 선택합니다.

.조사 보고서를 로컬로 다운로드합니다
BlueXP  분류는 데이터 조사 보고서를 로컬로 다운로드하여 브라우저에서 볼 수 있는 기능을 지원합니다. 로컬 옵션을 선택하면 데이터 조사는 CSV 형식으로만 사용할 수 있으며 처음 10,000개의 데이터 행만 표시됩니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["BlueXP  분류를 통해 조직에 저장된 데이터를 조사합니다"]참조하십시오.



== 2025년 3월 10일



=== 버전 1.41

이 BlueXP  분류 릴리스에는 일반적인 개선 사항 및 버그 수정이 포함되어 있습니다. 여기에는 다음이 포함됩니다.

.스캔 상태
BlueXP  분류는 볼륨에서 _initial_mapping 및 분류 스캔의 실시간 진행 상황을 추적합니다. 별도의 프로그레시브 바는 매핑 및 분류 스캔을 추적하여 스캔된 총 파일의 백분율을 표시합니다. 진행 표시줄 위로 마우스를 가져가면 스캔한 파일 수와 총 파일 수를 볼 수도 있습니다. 스캔 상태를 추적하면 스캔 진행 상황을 더 자세히 파악할 수 있으므로 스캔 계획을 개선하고 리소스 할당을 이해할 수 있습니다.

스캔 상태를 보려면 BlueXP  분류에서 ** 구성**으로 이동한 다음 ** 작업 환경 구성** 을 선택합니다. 진행 상황은 각 볼륨에 대해 일렬로 표시됩니다.



== 2025년 2월 19일



=== 버전 1.40

이 BlueXP  분류 릴리스에는 다음 업데이트가 포함됩니다.

.RHEL 9.5 지원
이 릴리스는 Red Hat Enterprise Linux v9.5 및 이전에 지원되는 버전을 지원합니다. 이는 다크 사이트 배포를 포함하여 BlueXP  분류의 수동 온-프레미스 설치에 적용됩니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.

.매핑 전용 스캔의 우선 순위를 지정합니다
매핑 전용 스캔을 수행할 때 가장 중요한 스캔의 우선 순위를 지정할 수 있습니다. 이 기능은 작업 환경이 많고 우선 순위가 높은 검사가 먼저 완료되도록 하려는 경우에 유용합니다.

기본적으로 스캔은 시작된 순서에 따라 대기합니다. 스캔 우선 순위 지정 기능을 통해 스캔을 대기열 앞으로 이동할 수 있습니다. 여러 스캔의 우선 순위를 지정할 수 있습니다. 우선 순위는 선입선출 순서로 지정됩니다. 즉, 우선 순위를 지정한 첫 번째 스캔이 대기열의 맨 앞으로 이동하고 우선 순위를 지정한 두 번째 스캔은 대기열의 두 번째 스캔이 됩니다.

우선 순위는 한 번만 부여됩니다. 매핑 데이터의 자동 재검색이 기본 순서로 수행됩니다.

우선 순위 지정은 로 link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["매핑 전용 스캔"^]제한됩니다. 스캔 맵과 분류에는 사용할 수 없습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"^]참조하십시오.

.모든 스캔을 재시도합니다
BlueXP  분류는 실패한 모든 스캔을 일괄 재시도하는 기능을 지원합니다.

** Retry All** 기능을 사용하여 일괄 작업으로 스캔을 다시 시도할 수 있습니다. 네트워크 중단과 같은 일시적인 문제로 인해 분류 스캔이 실패하는 경우 개별적으로 다시 시도하지 않고 하나의 버튼으로 모든 스캔을 동시에 다시 시도할 수 있습니다. 스캔은 필요한 만큼 재시도할 수 있습니다.

모든 스캔을 재시도하려면:

. BlueXP  classification 메뉴에서 * Configuration * 을 선택합니다.
. 실패한 모든 스캔을 다시 시도하려면 * 모든 스캔 재시도 * 를 선택합니다.


.범주화 모델 정확도 향상
의 머신 러닝 모델의 정확도는 link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["미리 정의된 범주"]11% 향상되었습니다.



== 2025년 1월 22일



=== 버전 1.39

이 BlueXP  분류 릴리스는 데이터 조사 보고서의 내보내기 프로세스를 업데이트합니다. 이 내보내기 업데이트는 데이터에 대한 추가 분석을 수행하거나, 데이터에 대한 추가 시각화를 만들거나, 데이터 조사 결과를 다른 사람과 공유하는 데 유용합니다.

이전에는 데이터 조사 보고서 내보내기가 10,000행으로 제한되었습니다. 이 릴리스에서는 모든 데이터를 내보낼 수 있도록 제한이 제거되었습니다. 이 변경 사항을 통해 데이터 조사 보고서에서 더 많은 데이터를 내보낼 수 있으므로 보다 유연하게 데이터를 분석할 수 있습니다.

작업 환경, 볼륨, 대상 폴더 및 JSON 또는 CSV 형식을 선택할 수 있습니다. 내보낸 파일 이름에는 타임스탬프가 포함되어 있어 데이터를 내보낸 시기를 식별할 수 있습니다.

지원되는 작업 환경은 다음과 같습니다.

* Cloud Volumes ONTAP
* ONTAP용 FSX
* ONTAP
* 공유 그룹


데이터 조사 보고서에서 데이터를 내보내는 데는 다음과 같은 제한 사항이 있습니다.

* 다운로드할 최대 레코드 수는 유형(파일, 디렉터리 및 테이블)당 5억 개입니다.
* 100만 개의 레코드를 내보내는 데 약 35분이 걸릴 것으로 예상됩니다.


데이터 조사 및 보고서에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["조직에 저장된 데이터를 조사합니다"].



== 2024년 12월 16일



=== 버전 1.38

이 BlueXP  분류 릴리스에는 일반적인 개선 사항 및 버그 수정이 포함되어 있습니다.



== 2024년 11월 4일



=== 버전 1.37

이 BlueXP  분류 릴리스에는 다음 업데이트가 포함됩니다.

.RHEL 8.10 지원
이 릴리스는 Red Hat Enterprise Linux v8.10 및 이전에 지원되는 버전을 지원합니다. 이는 다크 사이트 배포를 포함하여 BlueXP  분류의 수동 온-프레미스 설치에 적용됩니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3 및 9.4.

에 대해 자세히 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP 분류"]알아보십시오.

.NFS v4.1 지원
이 릴리즈에서는 이전에 지원된 버전 외에 NFS v4.1에 대한 지원도 제공합니다.

에 대해 자세히 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP 분류"]알아보십시오.



== 2024년 10월 10일



=== 버전 1.36

.RHEL 9.4 지원
이 릴리스는 Red Hat Enterprise Linux v9.4 및 이전에 지원되는 버전을 지원합니다. 이는 다크 사이트 배포를 포함하여 BlueXP  분류의 수동 온-프레미스 설치에 적용됩니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 9.0, 9.1, 9.2, 9.3 및 9.4.

에 대해 자세히 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["BlueXP 분류 구축 개요"]알아보십시오.

.향상된 스캔 성능
이번 릴리스에서는 향상된 스캔 성능을 제공합니다.



== 2024년 9월 2일



=== 버전 1.35

.StorageGRID 데이터를 스캔합니다
BlueXP  분류는 StorageGRID에서 데이터 스캔을 지원합니다.

자세한 내용은 을 link:task-scanning-storagegrid.html["StorageGRID 데이터를 스캔합니다"]참조하십시오.



== 2024년 8월 5일



=== 버전 1.34

이 BlueXP  분류 릴리스에는 다음 업데이트가 포함됩니다.

.CentOS에서 Ubuntu로 변경합니다
BlueXP  분류는 Microsoft Azure 및 Google Cloud Platform (GCP)용 Linux 운영 체제를 CentOS 7.9에서 Ubuntu 22.04로 업데이트했습니다.

배포 세부 정보는 을 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system["인터넷에 액세스할 수 있는 Linux 호스트에 설치하고 Linux 호스트 시스템을 준비합니다"]참조하십시오.



== 2024년 7월 1일



=== 버전 1.33

.Ubuntu 지원
이 릴리스는 Ubuntu 24.04 Linux 플랫폼을 지원합니다.

.매핑 검사는 메타데이터를 수집합니다
다음 메타데이터는 매핑 검사 중에 파일에서 추출되며 거버넌스, 규정 준수 및 조사 대시보드에 표시됩니다.

* 작업 환경
* 작업 환경 유형입니다
* 저장소 저장소
* 파일 형식
* 사용된 용량입니다
* 파일 수입니다
* 파일 크기
* 파일 생성
* 파일 마지막 액세스
* 파일이 마지막으로 수정되었습니다
* 파일 검색 시간
* 권한 추출


.대시보드의 추가 데이터
이 릴리스는 매핑 검사 중에 거버넌스, 규정 준수 및 조사 대시보드에 표시되는 데이터를 업데이트합니다.

자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["매핑 스캔과 분류 스캔의 차이점은 무엇입니까"].



== 2024년 6월 5일



=== 버전 1.32

.구성 페이지의 새 매핑 상태 열
이 릴리즈는 이제 구성 페이지에 새 매핑 상태 열을 표시합니다. 새 열을 통해 매핑이 실행 중인지, 대기열에 있는지, 일시 중지되었는지 등을 확인할 수 있습니다.

상태에 대한 설명은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html["스캔 설정을 변경합니다"].



== 2024년 5월 15일



=== 버전 1.31

.BlueXP 내에서 핵심 서비스로 분류할 수 있습니다
BlueXP classification 이제 커넥터당 최대 500TiB의 스캔 데이터에 대해 추가 비용 없이 BlueXP 의 핵심 기능으로 제공됩니다. 분류 라이선스 또는 유료 가입이 필요하지 않습니다. 이 새 버전으로 NetApp 스토리지 시스템을 검사하는 데 BlueXP 분류 기능을 집중하므로 일부 기존 기능은 이전에 라이센스 비용을 지불한 고객에게만 제공됩니다. 이러한 레거시 기능의 사용은 유료 계약이 종료일에 도달하면 만료됩니다.


NOTE: BlueXP classification 스캔할 수 있는 데이터 양에 제한을 두지 않습니다.  각 커넥터는 500TiB의 데이터 스캐닝과 표시를 지원합니다.  500TiB 이상의 데이터를 스캔하려면link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#connector-installation["다른 커넥터를 설치하세요"^] 그 다음에link:https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["BlueXP classification 의 또 다른 인스턴스를 배포합니다."] .  BlueXP UI는 단일 커넥터의 데이터를 표시합니다.  여러 커넥터에서 데이터를 보는 방법에 대한 팁은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["여러 개의 커넥터로 작업합니다"^] .

link:reference-free-paid.html["더 이상 사용되지 않는 기능에 대해 자세히 알아보십시오"]..



== 2024년 4월 1일



=== 버전 1.30

.RHEL v8.8 및 v9.3 BlueXP 분류에 대한 지원이 추가되었습니다
이 릴리스는 이전에 지원되는 9.x 외에도 Red Hat Enterprise Linux v8.8 및 v9.3에 대한 지원을 제공하며, Docker 엔진 대신 Podman이 필요합니다. 이는 BlueXP 분류의 수동 온프레미스 설치에 적용할 수 있습니다.

Podman 컨테이너 엔진을 사용해야 하는 운영 체제에는 BlueXP 분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 9.0, 9.1, 9.2 및 9.3 이상이 필요합니다.

에 대해 자세히 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["BlueXP 분류 구축 개요"]알아보십시오.

Connector를 사내에 상주하는 RHEL 8 또는 9 호스트에 설치하는 경우 BlueXP 분류가 지원됩니다. RHEL 8 또는 9 호스트가 AWS, Azure 또는 Google Cloud에 상주하는 경우에는 지원되지 않습니다.

.감사 로그 수집을 활성화하는 옵션이 제거되었습니다
감사 로그 수집을 활성화하는 옵션이 비활성화되었습니다.

.스캔 속도가 향상되었습니다
보조 스캐너 노드의 스캔 성능이 향상되었습니다. 스캔 처리 능력이 추가로 필요한 경우 스캐너 노드를 더 추가할 수 있습니다. 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["인터넷에 액세스할 수 있는 호스트에 BlueXP 분류를 설치합니다"]참조하십시오.

.자동 업그레이드
인터넷에 액세스할 수 있는 시스템에 BlueXP 분류를 구축한 경우 시스템이 자동으로 업그레이드됩니다. 이전에는 마지막 사용자 작업 이후 특정 시간이 경과한 후에 업그레이드가 발생했습니다. 이 릴리즈에서는 현지 시간이 오전 1시에서 오전 5시 사이인 경우 BlueXP  분류가 자동으로 업그레이드됩니다. 로컬 시간이 이 시간을 벗어난 경우 마지막 사용자 작업 이후 특정 시간이 경과하면 업그레이드가 수행됩니다. 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["인터넷에 액세스할 수 있는 Linux 호스트에 설치합니다"]참조하십시오.

인터넷에 액세스하지 않고 BlueXP 분류를 구축한 경우 수동으로 업그레이드해야 합니다. 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-dark-site.html["인터넷에 액세스할 수 없는 Linux 호스트에 BlueXP 분류를 설치합니다"]참조하십시오.



== 2024년 3월 4일



=== 버전 1.29

.이제 특정 데이터 소스 디렉토리에 있는 데이터 검사를 제외할 수 있습니다
BlueXP 분류를 통해 특정 데이터 소스 디렉토리에 있는 스캔 데이터를 제외하려면 이러한 디렉토리 이름을 BlueXP 분류 프로세스를 수행하는 구성 파일에 추가할 수 있습니다. 이 기능을 사용하면 불필요한 디렉터리를 검색하지 않거나 잘못된 개인 데이터 결과를 반환할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["자세한 정보"]..

.이제 더 큰 인스턴스 지원이 가능합니다
2억 5천만 개 이상의 파일을 스캔하기 위해 BlueXP 분류가 필요한 경우 클라우드 구축 또는 온프레미스 설치에서 초대형 인스턴스를 사용할 수 있습니다. 이 유형의 시스템은 최대 5억 개의 파일을 스캔할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["자세한 정보"]..



== 2024년 1월 10일



=== 버전 1.27

.조사 페이지 결과에는 총 항목 수와 함께 총 크기가 표시됩니다
조사 페이지의 필터링된 결과에는 총 파일 수와 함께 항목의 총 크기가 표시됩니다. 이 기능은 파일 이동, 파일 삭제 등에 도움이 될 수 있습니다.

.추가 그룹 ID를 "조직에 열기"로 구성
이제 그룹이 처음에 해당 권한으로 설정되지 않은 경우, NFS의 그룹 ID를 BlueXP 분류에서 직접 "Open to Organization"으로 간주하도록 구성할 수 있습니다. 이러한 그룹 ID가 첨부된 파일 및 폴더는 조사 세부 정보 페이지에서 "조직에 열기"로 표시됩니다. 방법 보기 https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["추가 그룹 ID를 "조직에 열려 있음"으로 추가"].



== 2023년 12월 14일



=== 버전 1.26.6

이 릴리스에는 몇 가지 사소한 개선 사항이 포함되어 있습니다.

이 릴리스에서는 다음 옵션도 제거되었습니다.

* 감사 로그 수집을 활성화하는 옵션이 비활성화되었습니다.
* 디렉터리 조사 중에는 디렉터리별 개인 식별 정보(PII) 데이터 수를 계산하는 옵션을 사용할 수 없습니다. 을 link:task-investigate-data.html["조직에 저장된 데이터를 조사합니다"]참조하십시오.
* AIP(Azure Information Protection) 레이블을 사용하여 데이터를 통합하는 옵션이 비활성화되었습니다. 을 link:task-org-private-data.html["개인 데이터를 구성합니다"]참조하십시오.




== 2023년 11월 6일



=== 버전 1.26.3

이 릴리스에서는 다음 문제가 해결되었습니다

* 시스템에서 스캔된 파일 수를 대시보드에 표시할 때 불일치 문제가 해결되었습니다.
* 이름 및 메타데이터에 특수 문자가 있는 파일과 디렉터리를 처리하고 보고함으로써 검색 동작을 개선했습니다.




== 2023년 10월 4일



=== 버전 1.26

.RHEL 버전 9에서 BlueXP 분류의 사내 설치를 지원합니다
Red Hat Enterprise Linux 버전 8 및 9은 BlueXP 분류 설치에 필요한 Docker 엔진을 지원하지 않습니다. 현재 Podman 버전 4 이상을 컨테이너 인프라로 사용하여 RHEL 9.0, 9.1 및 9.2에서 BlueXP 분류 설치를 지원합니다. 환경에 최신 버전의 RHEL을 사용해야 하는 경우 이제 Podman을 사용할 때 BlueXP 분류(버전 1.26 이상)를 설치할 수 있습니다.

현재 RHEL 9.x를 사용하는 경우 다크 사이트 설치 또는 분산 스캐닝 환경(마스터 및 원격 스캐너 노드 사용)은 지원되지 않습니다



== 2023년 9월 5일



=== 버전 1.25

.중소 규모 구축은 일시적으로 사용할 수 없습니다
AWS에 BlueXP 분류의 인스턴스를 구축할 때 * Deploy > Configuration * 을 선택하고 소형 또는 중형 인스턴스를 선택하는 옵션은 현재 사용할 수 없습니다. Deploy > Deploy * 를 선택하여 대규모 인스턴스 크기를 사용하여 인스턴스를 배포할 수 있습니다.

.조사 결과 페이지에서 최대 100,000개의 항목에 태그를 적용합니다
이전에는 조사 결과 페이지에서 한 번에 한 페이지에만 태그를 적용할 수 있었습니다(20개 항목). 이제 조사 결과 페이지에서 * 모든 * 항목을 선택하고 모든 항목에 태그를 적용할 수 있습니다. 한 번에 최대 100,000개 항목까지 가능합니다. https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["방법을 확인하십시오"]..

.최소 파일 크기가 1MB인 중복 파일을 식별합니다
BlueXP 분류는 파일이 50MB 이상인 경우에만 중복된 파일을 식별하는 데 사용됩니다. 이제 1MB로 시작하는 중복 파일을 식별할 수 있습니다. 조사 페이지에서 "파일 크기"와 "중복 항목"을 필터링하여 사용자 환경에서 특정 크기의 파일이 복제되었는지 확인할 수 있습니다.



== 2023년 7월 17일



=== 버전 1.24

.BlueXP 분류에서는 두 가지 새로운 유형의 독일 개인 데이터를 식별합니다
BlueXP 분류는 다음과 같은 유형의 데이터가 포함된 파일을 식별하고 분류할 수 있습니다.

* 독일어 ID(Personalausweummer)
* 독일 사회 보장 번호(소지아버서머스무머)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["BlueXP 분류에서 데이터에서 식별할 수 있는 모든 개인 데이터 유형을 확인하십시오"]..

.BlueXP 분류는 제한 모드 및 비공개 모드에서 완전히 지원됩니다
BlueXP  분류는 현재 인터넷 액세스가 없는 사이트(비공개 모드)와 제한된 아웃바운드 인터넷 액세스(제한 모드)에서 완벽하게 지원됩니다. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Connector의 BlueXP 배포 모드에 대해 자세히 알아보십시오"^]..

.BlueXP 분류의 비공개 모드 설치를 업그레이드할 때 버전을 건너뛸 수 있습니다
이제 순차적이지 않더라도 최신 버전의 BlueXP 분류로 업그레이드할 수 있습니다. 즉, 한 번에 한 버전씩 BlueXP 분류를 업그레이드할 때 현재 제한이 없어진다는 의미입니다. 이 기능은 버전 1.24 이상부터 관련이 있습니다.

.BlueXP 분류 API가 이제 제공됩니다
BlueXP 분류 API를 사용하면 작업을 수행하고, 쿼리를 생성하고, 스캔하는 데이터에 대한 정보를 내보낼 수 있습니다. 대화형 설명서는 Swagger를 사용하여 사용할 수 있습니다. 문서는 조사, 규정 준수, 거버넌스 및 구성을 포함한 여러 범주로 구분됩니다. 각 범주는 BlueXP 분류 UI의 탭에 대한 참조입니다.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["BlueXP 분류 API에 관해 자세히 알아보십시오"]..



== 2023년 6월 6일



=== 버전 1.23

.이제 데이터 제목 이름을 검색할 때 일본어가 지원됩니다
Data Subject Access Request(SAR)에 대한 응답으로 시험대상자 이름을 검색할 때 일본어 이름을 입력할 수 있습니다. 결과 정보가 포함된 를 생성할 수 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html["데이터 주체 액세스 요청 보고서"] 있습니다. 에 일본어 이름을 입력하여 주체 이름이 포함된 파일을 식별할 수도 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["데이터 조사 페이지의 "데이터 제목" 필터"] 있습니다.

.Ubuntu는 이제 BlueXP 분류를 설치할 수 있는 지원되는 Linux 배포판입니다
Ubuntu 22.04는 BlueXP 분류에 지원되는 운영 체제로 검증되었습니다. 설치 프로그램의 버전 1.23을 사용하는 경우 네트워크의 Ubuntu Linux 호스트 또는 클라우드의 Linux 호스트에 BlueXP  분류를 설치할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Ubuntu가 설치된 호스트에 BlueXP 분류를 설치하는 방법을 참조하십시오"]..

.Red Hat Enterprise Linux 8.6과 8.7은 새로운 BlueXP 분류 설치에서 더 이상 지원되지 않습니다
Red Hat은 더 이상 Docker를 지원하지 않으므로 이러한 버전은 새로운 배포에서 지원되지 않습니다. RHEL 8.6 또는 8.7에서 기존 BlueXP 분류 시스템을 실행 중인 경우 NetApp는 계속해서 구성을 지원합니다.

.ONTAP 시스템에서 FPolicy 이벤트를 수신하려면 BlueXP 분류를 FPolicy Collector로 구성할 수 있습니다
BlueXP 분류 시스템에서 파일 액세스 감사 로그를 수집하여 작업 환경의 볼륨에서 감지된 파일 액세스 이벤트를 처리할 수 있습니다. BlueXP 분류는 다음 유형의 FPolicy 이벤트와 파일에서 작업을 수행한 사용자, 즉 만들기, 읽기, 쓰기, 삭제, 이름 바꾸기, 소유자/권한을 변경하고 SACL/DACL을 변경합니다.

.이제 Data Sense BYOL 라이센스가 다크 사이트에서 지원됩니다
이제 데이터 감지 BYOL 라이센스를 어두운 사이트의 BlueXP 디지털 지갑에 업로드하여 라이센스가 낮아지면 알림을 받을 수 있습니다.



== 2023년 4월 3일



=== 버전 1.22

.새로운 데이터 검색 평가 보고서
데이터 검색 평가 보고서는 스캔한 환경에 대한 상위 수준의 분석을 통해 시스템의 결과를 강조하고 문제 영역 및 잠재적인 개선 단계를 보여줍니다. 이 보고서의 목표는 데이터 거버넌스 문제, 데이터 보안 노출 및 데이터 규정 준수 격차에 대한 인식을 높이는 것입니다. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["데이터 검색 평가 보고서를 생성하고 사용하는 방법을 확인하십시오"]..

.클라우드 내 소규모 인스턴스에 BlueXP 분류 기능을 배포할 수 있습니다
AWS 환경의 BlueXP Connector에서 BlueXP 분류를 배포할 때 이제 기본 인스턴스에서 사용할 수 있는 것보다 두 가지 작은 인스턴스 유형 중에서 선택할 수 있습니다. 소규모 환경을 스캔하면 클라우드 비용을 절감할 수 있습니다. 그러나 더 작은 인스턴스를 사용할 때는 몇 가지 제한 사항이 있습니다. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["사용 가능한 인스턴스 유형 및 제한 사항을 참조하십시오"]..

.이제 BlueXP 분류 설치 전에 독립 실행형 스크립트를 사용하여 Linux 시스템을 검증할 수 있습니다
BlueXP  분류 설치 실행과 별도로 Linux 시스템이 모든 사전 요구 사항을 충족하는지 확인하려면 필수 구성 요소에 대한 테스트만 다운로드할 수 있는 별도의 스크립트가 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Linux 호스트가 BlueXP 분류를 설치할 준비가 되었는지 확인하는 방법을 참조하십시오"]..



== 2023년 3월 7일



=== 버전 1.21

.BlueXP 분류 UI에서 사용자 지정 범주를 추가하는 새로운 기능
이제 BlueXP 분류를 통해 사용자 지정 범주를 추가할 수 있으므로 BlueXP 분류에서 해당 범주에 적합한 파일을 식별할 수 있습니다. BlueXP  분류에는 많은 기능이 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["미리 정의된 범주"] 있으므로 이 기능을 사용하면 사용자 지정 범주를 추가하여 조직에서 고유한 정보를 데이터에서 찾을 수 있는 위치를 식별할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["자세한 정보"^]..

.이제 BlueXP 분류 UI에서 사용자 지정 키워드를 추가할 수 있습니다
BlueXP 분류에서는 BlueXP 분류가 향후 검색에서 식별할 수 있는 사용자 지정 키워드를 추가할 수 있었습니다. 그러나 BlueXP 분류 Linux 호스트에 로그인하고 명령줄 인터페이스를 사용하여 키워드를 추가해야 합니다. 이 릴리스에서 사용자 지정 키워드를 추가하는 기능은 BlueXP 분류 UI에 포함되어 있으므로 이러한 키워드를 쉽게 추가하고 편집할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["BlueXP 분류 UI에서 사용자 지정 키워드를 추가하는 방법에 대해 자세히 알아보십시오"^]..

."마지막 액세스 시간"이 변경될 때 BlueXP 분류 * 파일 * 스캔 기능이 없음
기본적으로 BlueXP 분류에 적절한 "쓰기" 권한이 없으면 BlueXP 분류가 "마지막 액세스 시간"을 원래 타임 스탬프로 되돌릴 수 없기 때문에 시스템에서 볼륨의 파일을 검색하지 않습니다. 그러나 파일의 마지막 액세스 시간이 원래 시간으로 재설정되는 것을 염려하지 않을 경우, BlueXP 분류가 권한에 관계없이 볼륨을 스캔하도록 구성 페이지에서 이 동작을 재정의할 수 있습니다.

이 기능과 함께 "Scan Analysis Event"라는 새 필터가 추가되어 BlueXP 분류로 마지막으로 액세스한 시간을 되돌릴 수 없거나, BlueXP 분류로 마지막으로 액세스한 시간을 되돌릴 수 없는 경우에도 분류된 파일을 볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html[""마지막 액세스 시간 타임스탬프" 및 BlueXP 분류에 필요한 권한에 대해 자세히 알아보십시오"]..

.BlueXP 분류에서는 세 가지 새로운 유형의 개인 데이터를 식별합니다
BlueXP 분류는 다음과 같은 유형의 데이터가 포함된 파일을 식별하고 분류할 수 있습니다.

* 보츠와나 ID 카드(오만) 번호
* 보츠와나 여권 번호
* 싱가포르 국가 등록 ID 카드(NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["BlueXP 분류에서 데이터에서 식별할 수 있는 모든 개인 데이터 유형을 확인하십시오"]..

.디렉토리의 기능이 업데이트되었습니다
* 이제 데이터 조사 보고서에 대한 "Light CSV Report(라이트 CSV 보고서)" 옵션에 디렉토리의 정보가 포함됩니다.
* 이제 "마지막 액세스" 시간 필터에 파일과 디렉터리 모두의 마지막 액세스 시간이 표시됩니다.


.설치 개선 사항
* 인터넷 접속(다크 사이트)이 없는 사이트의 BlueXP 분류 설치 관리자가 사전 검사를 수행하여 성공적인 설치를 위해 시스템 및 네트워킹 요구 사항이 제대로 갖추어져 있는지 확인합니다.
* 설치 감사 로그 파일은 지금 저장되며 에 `/ops/netapp/install_logs`기록됩니다.




== 2023년 2월 5일



=== 버전 1.20

.모든 이메일 주소로 정책 기반 알림 이메일을 보낼 수 있습니다
이전 버전의 BlueXP 분류에서는 특정 중요 정책이 결과를 반환할 때 계정의 BlueXP 사용자에게 전자 메일 알림을 보낼 수 있습니다. 이 기능을 사용하면 온라인 상태가 아닐 때 데이터를 보호하기 위한 알림을 받을 수 있습니다. 이제 BlueXP 계정에 없는 다른 모든 사용자(최대 20개의 이메일 주소)에게 정책의 이메일 알림을 보낼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["정책 결과를 기반으로 이메일 알림을 보내는 방법에 대해 자세히 알아보십시오"]..

.이제 BlueXP 분류 UI에서 개인 패턴을 추가할 수 있습니다
BlueXP 분류에서는 BlueXP 분류가 향후 검색에서 식별할 수 있는 맞춤형 "개인 데이터"를 추가할 수 있었습니다. 그러나 BlueXP 분류 Linux 호스트에 로그인하고 명령줄을 사용하여 사용자 지정 패턴을 추가해야 합니다. 이번 릴리스에서는 BlueXP 분류 UI에 regex를 사용하여 개인 패턴을 추가할 수 있으므로 이러한 사용자 지정 패턴을 쉽게 추가하고 편집할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["BlueXP 분류 UI에서 사용자 지정 패턴을 추가하는 방법에 대해 자세히 알아보십시오"^]..

.BlueXP 분류를 사용하여 1500만 개의 파일을 이동할 수 있습니다
과거에는 BlueXP 분류로 최대 100,000개의 소스 파일을 NFS 공유로 이동할 수 있었습니다. 이제 한 번에 최대 1500만 개의 파일을 이동할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html["BlueXP 분류를 사용하여 소스 파일을 이동하는 방법에 대해 자세히 알아보십시오"]..

.SharePoint Online 파일에 액세스할 수 있는 사용자 수를 볼 수 있습니다
"액세스 권한이 있는 사용자 수" 필터는 이제 SharePoint Online 리포지토리에 저장된 파일을 지원합니다. 이전에는 CIFS 공유의 파일만 지원되었습니다. Active Directory 기반이 아닌 SharePoint 그룹은 현재 이 필터에서 계산되지 않습니다.

.새 "부분 성공" 상태가 작업 상태 패널에 추가되었습니다
새로운 "부분 성공" 상태는 BlueXP 분류 작업이 완료되었고 일부 항목이 실패했으며 100개의 파일을 이동하거나 삭제하는 등 일부 항목이 성공했음을 나타냅니다. 또한 "완료됨" 상태의 이름이 "성공"으로 변경되었습니다. 과거에는 "완료" 상태에 성공했고 실패한 작업이 나열될 수 있습니다. 이제 "성공" 상태는 모든 작업이 모든 항목에 성공했음을 의미합니다. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["작업 상태 패널을 보는 방법을 참조하십시오"]..



== 2023년 1월 9일



=== 버전 1.19

.중요한 데이터가 포함되어 있고 지나치게 허용적인 파일 차트를 볼 수 있는 기능
Governance 대시보드에는 중요한 데이터(민감한 개인 데이터 및 민감한 개인 데이터 포함)를 포함하고 지나치게 허용적인 파일의 열 지도를 제공하는 새로운 _Sensitive Data 및 Wide Permissions_영역이 추가되었습니다. 이렇게 하면 중요한 데이터와 관련하여 몇 가지 위험이 있을 수 있는 위치를 파악할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["자세한 정보"]..

.데이터 조사 페이지에서 3개의 새 필터를 사용할 수 있습니다
새 필터를 사용하여 데이터 조사 페이지에 표시되는 결과를 구체화할 수 있습니다.

* "액세스 권한이 있는 사용자 수" 필터는 특정 수의 사용자에게 열려 있는 파일과 폴더를 표시합니다. 숫자 범위를 선택하여 결과를 구체화할 수 있습니다. 예를 들어 51-100명의 사용자가 액세스할 수 있는 파일을 확인할 수 있습니다.
* 이제 "Created Time(생성 시간)", "Discovered Time(검색 시간)", "Last Modified(마지막 수정)" 및 "Last Accessed(마지막 액세스)" 필터를 사용하여 미리 정의된 날짜 범위를 선택하는 대신 사용자 지정 날짜 범위를 만들 수 있습니다. 예를 들어 "만든 시간", "6개월 이전" 또는 "최근 10일" 내의 "마지막으로 수정한 날짜"가 있는 파일을 찾을 수 있습니다.
* 이제 "파일 경로" 필터를 사용하여 필터링된 쿼리 결과에서 제외할 경로를 지정할 수 있습니다. 특정 데이터를 포함 및 제외하기 위한 경로를 입력하면 BlueXP 분류에서 포함된 경로의 모든 파일을 먼저 찾은 다음 제외된 경로에서 파일을 제거한 다음 결과를 표시합니다.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하십시오"]..

.BlueXP 분류는 일본어 개인 번호를 식별할 수 있습니다
BlueXP 분류는 일본어 개인 번호(내 번호라고도 함)가 포함된 파일을 식별하고 분류할 수 있습니다. 여기에는 개인 번호와 회사 내 번호가 모두 포함됩니다. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["BlueXP 분류에서 데이터에서 식별할 수 있는 모든 개인 데이터 유형을 확인하십시오"]..
