---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: BlueXP 분류의 새로운 기능에 대해 알아보십시오. 
---
= BlueXP 분류의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 분류의 새로운 기능에 대해 알아보십시오.



== 9월 5일(버전 1.25)



=== 조사 결과 페이지에서 최대 100,000개의 항목에 태그를 적용합니다

이전에는 조사 결과 페이지에서 한 번에 한 페이지에만 태그를 적용할 수 있었습니다(20개 항목). 이제 조사 결과 페이지에서 * 모든 * 항목을 선택하고 모든 항목에 태그를 적용할 수 있습니다. 한 번에 최대 100,000개 항목까지 가능합니다.  https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assigning-tags-to-files["방법을 확인하십시오"].



=== 최소 파일 크기가 1MB인 중복 파일을 식별합니다

BlueXP 분류는 파일이 50MB 이상인 경우에만 중복된 파일을 식별하는 데 사용됩니다. 이제 1MB로 시작하는 중복 파일을 식별할 수 있습니다. 조사 페이지에서 "파일 크기"와 "중복 항목"을 필터링하여 사용자 환경에서 특정 크기의 파일이 복제되었는지 확인할 수 있습니다.



== 2023년 7월 17일(버전 1.24)



=== BlueXP 분류에서는 두 가지 새로운 유형의 독일 개인 데이터를 식별합니다

BlueXP 분류는 다음과 같은 유형의 데이터가 포함된 파일을 식별하고 분류할 수 있습니다.

* 독일어 ID(Personalausweummer)
* 독일 사회 보장 번호(소지아버서머스무머)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["BlueXP 분류에서 데이터에서 식별할 수 있는 모든 개인 데이터 유형을 확인하십시오"].



=== Rocky Linux 9는 이제 BlueXP 분류를 설치할 수 있는 Linux 배포판입니다

Rocky Linux 9(9.0, 9.1 및 9.2)는 BlueXP 분류에서 지원되는 운영 체제로 인증되었습니다. 설치 프로그램의 1.24 버전을 사용하는 경우, 네트워크의 Rocky Linux 호스트 또는 클라우드의 Linux 호스트에 BlueXP 분류를 설치할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Rocky Linux가 설치된 호스트에 BlueXP 분류를 설치하는 방법을 확인하십시오"].



=== BlueXP 분류는 제한 모드 및 비공개 모드에서 완전히 지원됩니다

현재 BlueXP 분류는 인터넷 액세스(비공개 모드)가 없는 사이트와 제한된 아웃바운드 인터넷 액세스(제한 모드)에서 완벽하게 지원됩니다. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Connector의 BlueXP 배포 모드에 대해 자세히 알아보십시오"^].



=== BlueXP 분류의 비공개 모드 설치를 업그레이드할 때 버전을 건너뛸 수 있습니다

이제 순차적이지 않더라도 최신 버전의 BlueXP 분류로 업그레이드할 수 있습니다. 즉, 한 번에 한 버전씩 BlueXP 분류를 업그레이드할 때 현재 제한이 없어진다는 의미입니다. 이 기능은 버전 1.24 이상부터 관련이 있습니다.



=== BlueXP 분류 API가 이제 제공됩니다

BlueXP 분류 API를 사용하면 작업을 수행하고, 쿼리를 생성하고, 스캔하는 데이터에 대한 정보를 내보낼 수 있습니다. 대화형 설명서는 Swagger를 사용하여 사용할 수 있습니다. 문서는 조사, 규정 준수, 거버넌스 및 구성을 포함한 여러 범주로 구분됩니다. 각 범주는 BlueXP 분류 UI의 탭에 대한 참조입니다.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["BlueXP 분류 API에 관해 자세히 알아보십시오"].



== 2023년 6월 6일(버전 1.23)



=== 이제 데이터 제목 이름을 검색할 때 일본어가 지원됩니다

Data Subject Access Request(SAR)에 대한 응답으로 시험대상자 이름을 검색할 때 일본어 이름을 입력할 수 있습니다. 을 생성할 수 있습니다 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#what-is-a-data-subject-access-request["데이터 주체 액세스 요청 보고서"] 결과 정보를 사용합니다. 에 일본어 이름을 입력할 수도 있습니다 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-by-sensitivity-and-content["데이터 조사 페이지의 "데이터 제목" 필터"] 제목 이름이 포함된 파일을 식별합니다.



=== Ubuntu는 이제 BlueXP 분류를 설치할 수 있는 지원되는 Linux 배포판입니다

Ubuntu 22.04는 BlueXP 분류에 지원되는 운영 체제로 검증되었습니다. 설치 프로그램의 버전 1.23을 사용하는 경우 네트워크의 Ubuntu Linux 호스트 또는 클라우드의 Linux 호스트에 BlueXP 분류를 설치할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Ubuntu가 설치된 호스트에 BlueXP 분류를 설치하는 방법을 참조하십시오"].



=== Red Hat Enterprise Linux 8.6과 8.7은 새로운 BlueXP 분류 설치에서 더 이상 지원되지 않습니다

Red Hat은 더 이상 Docker를 지원하지 않으므로 이러한 버전은 새로운 배포에서 지원되지 않습니다. RHEL 8.6 또는 8.7에서 기존 BlueXP 분류 시스템을 실행 중인 경우 NetApp는 계속해서 구성을 지원합니다.



=== ONTAP 시스템에서 FPolicy 이벤트를 수신하려면 BlueXP 분류를 FPolicy Collector로 구성할 수 있습니다

BlueXP 분류 시스템에서 파일 액세스 감사 로그를 수집하여 작업 환경의 볼륨에서 감지된 파일 액세스 이벤트를 처리할 수 있습니다. BlueXP 분류는 다음 유형의 FPolicy 이벤트와 파일에서 작업을 수행한 사용자, 즉 만들기, 읽기, 쓰기, 삭제, 이름 바꾸기, 소유자/권한을 변경하고 SACL/DACL을 변경합니다. https://docs.netapp.com/us-en/bluexp-classification/task-manage-file-access-events.html["파일 액세스 이벤트를 모니터링하고 관리하는 방법을 확인하십시오"].



=== 이제 Data Sense BYOL 라이센스가 다크 사이트에서 지원됩니다

이제 데이터 감지 BYOL 라이센스를 어두운 사이트의 BlueXP 디지털 지갑에 업로드하여 라이센스가 낮아지면 알림을 받을 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file["Data Sense BYOL 라이센스를 획득하고 업로드하는 방법을 알아보십시오"].



== 2023년 4월 3일(버전 1.22)



=== 새로운 데이터 검색 평가 보고서

데이터 검색 평가 보고서는 스캔한 환경에 대한 상위 수준의 분석을 통해 시스템의 결과를 강조하고 문제 영역 및 잠재적인 개선 단계를 보여줍니다. 이 보고서의 목표는 데이터 거버넌스 문제, 데이터 보안 노출 및 데이터 세트의 데이터 규정 준수 공백에 대한 인식을 높이는 것입니다. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["데이터 검색 평가 보고서를 생성하고 사용하는 방법을 확인하십시오"].



=== 클라우드 내 소규모 인스턴스에 BlueXP 분류 기능을 배포할 수 있습니다

AWS 환경의 BlueXP Connector에서 BlueXP 분류를 배포할 때 이제 기본 인스턴스에서 사용할 수 있는 것보다 두 가지 작은 인스턴스 유형 중에서 선택할 수 있습니다. 소규모 환경을 스캔하면 클라우드 비용을 절감할 수 있습니다. 그러나 더 작은 인스턴스를 사용할 때는 몇 가지 제한 사항이 있습니다. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["사용 가능한 인스턴스 유형 및 제한 사항을 참조하십시오"].



=== 이제 BlueXP 분류 설치 전에 독립 실행형 스크립트를 사용하여 Linux 시스템을 검증할 수 있습니다

Linux 시스템이 BlueXP 분류 설치를 실행하는 것과 관계없이 모든 필수 구성 요소를 충족하는지 확인하려면 사전 요구 사항에 대한 테스트만 다운로드할 수 있는 별도의 스크립트가 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Linux 호스트가 BlueXP 분류를 설치할 준비가 되었는지 확인하는 방법을 참조하십시오"].



== 2023년 3월 7일(버전 1.21)



=== BlueXP 분류 UI에서 사용자 지정 범주를 추가하는 새로운 기능

이제 BlueXP 분류를 통해 사용자 지정 범주를 추가할 수 있으므로 BlueXP 분류에서 해당 범주에 적합한 파일을 식별할 수 있습니다. BlueXP 분류에는 많은 기능이 있습니다 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["미리 정의된 범주"]따라서 이 기능을 사용하면 사용자 지정 범주를 추가하여 조직에서 고유한 정보를 데이터에서 찾을 위치를 식별할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["자세한 정보"^].



=== 이제 BlueXP 분류 UI에서 사용자 지정 키워드를 추가할 수 있습니다

BlueXP 분류에서는 BlueXP 분류가 향후 검색에서 식별할 수 있는 사용자 지정 키워드를 추가할 수 있었습니다. 그러나 BlueXP 분류 Linux 호스트에 로그인하고 명령줄 인터페이스를 사용하여 키워드를 추가해야 합니다. 이 릴리스에서 사용자 지정 키워드를 추가하는 기능은 BlueXP 분류 UI에 포함되어 있으므로 이러한 키워드를 쉽게 추가하고 편집할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["BlueXP 분류 UI에서 사용자 지정 키워드를 추가하는 방법에 대해 자세히 알아보십시오"^].



=== "마지막 액세스 시간"이 변경될 때 BlueXP 분류 * 파일 * 스캔 기능이 없음

기본적으로 BlueXP 분류에 적절한 "쓰기" 권한이 없으면 BlueXP 분류가 "마지막 액세스 시간"을 원래 타임 스탬프로 되돌릴 수 없기 때문에 시스템에서 볼륨의 파일을 검색하지 않습니다. 그러나 파일의 마지막 액세스 시간이 원래 시간으로 재설정되는 것을 염려하지 않을 경우, BlueXP 분류가 권한에 관계없이 볼륨을 스캔하도록 구성 페이지에서 이 동작을 재정의할 수 있습니다.

이 기능과 함께 "Scan Analysis Event"라는 새 필터가 추가되어 BlueXP 분류로 마지막으로 액세스한 시간을 되돌릴 수 없거나, BlueXP 분류로 마지막으로 액세스한 시간을 되돌릴 수 없는 경우에도 분류된 파일을 볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp[""마지막 액세스 시간 타임스탬프" 및 BlueXP 분류에 필요한 권한에 대해 자세히 알아보십시오"].



=== BlueXP 분류에서는 세 가지 새로운 유형의 개인 데이터를 식별합니다

BlueXP 분류는 다음과 같은 유형의 데이터가 포함된 파일을 식별하고 분류할 수 있습니다.

* 보츠와나 ID 카드(오만) 번호
* 보츠와나 여권 번호
* 싱가포르 국가 등록 ID 카드(NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["BlueXP 분류에서 데이터에서 식별할 수 있는 모든 개인 데이터 유형을 확인하십시오"].



=== 디렉토리의 기능이 업데이트되었습니다

* 이제 데이터 조사 보고서에 대한 "Light CSV Report(라이트 CSV 보고서)" 옵션에 디렉토리의 정보가 포함됩니다.
* 이제 "마지막 액세스" 시간 필터에 파일과 디렉터리 모두의 마지막 액세스 시간이 표시됩니다.




=== 설치 개선 사항

* 인터넷 접속(다크 사이트)이 없는 사이트의 BlueXP 분류 설치 관리자가 사전 검사를 수행하여 성공적인 설치를 위해 시스템 및 네트워킹 요구 사항이 제대로 갖추어져 있는지 확인합니다.
* 설치 감사 로그 파일은 지금 저장되며 에 기록됩니다 `/ops/netapp/install_logs`.




== 2023년 2월 5일(버전 1.20)



=== 모든 이메일 주소로 정책 기반 알림 이메일을 보낼 수 있습니다

이전 버전의 BlueXP 분류에서는 특정 중요 정책이 결과를 반환할 때 계정의 BlueXP 사용자에게 전자 메일 알림을 보낼 수 있습니다. 이 기능을 사용하면 온라인 상태가 아닐 때 데이터를 보호하기 위한 알림을 받을 수 있습니다. 이제 BlueXP 계정에 없는 다른 모든 사용자(최대 20개의 이메일 주소)에게 정책의 이메일 알림을 보낼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["정책 결과를 기반으로 이메일 알림을 보내는 방법에 대해 자세히 알아보십시오"].



=== 이제 BlueXP 분류 UI에서 개인 패턴을 추가할 수 있습니다

BlueXP 분류에서는 BlueXP 분류가 향후 검색에서 식별할 수 있는 맞춤형 "개인 데이터"를 추가할 수 있었습니다. 그러나 BlueXP 분류 Linux 호스트에 로그인하고 명령줄을 사용하여 사용자 지정 패턴을 추가해야 합니다. 이번 릴리스에서는 BlueXP 분류 UI에 regex를 사용하여 개인 패턴을 추가할 수 있으므로 이러한 사용자 지정 패턴을 쉽게 추가하고 편집할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["BlueXP 분류 UI에서 사용자 지정 패턴을 추가하는 방법에 대해 자세히 알아보십시오"^].



=== BlueXP 분류를 사용하여 1500만 개의 파일을 이동할 수 있습니다

과거에는 BlueXP 분류로 최대 100,000개의 소스 파일을 NFS 공유로 이동할 수 있었습니다. 이제 한 번에 최대 1,500만 개의 파일을 이동할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["BlueXP 분류를 사용하여 소스 파일을 이동하는 방법에 대해 자세히 알아보십시오"].



=== SharePoint Online 파일에 액세스할 수 있는 사용자 수를 볼 수 있습니다

"액세스 권한이 있는 사용자 수" 필터는 이제 SharePoint Online 리포지토리에 저장된 파일을 지원합니다. 이전에는 CIFS 공유의 파일만 지원되었습니다. Active Directory 기반이 아닌 SharePoint 그룹은 현재 이 필터에서 계산되지 않습니다.



=== 새 "부분 성공" 상태가 작업 상태 패널에 추가되었습니다

새로운 "부분 성공" 상태는 BlueXP 분류 작업이 완료되었고 일부 항목이 실패했으며 100개의 파일을 이동하거나 삭제하는 등 일부 항목이 성공했음을 나타냅니다. 또한 "완료됨" 상태의 이름이 "성공"으로 변경되었습니다. 과거에는 "완료" 상태에 성공했고 실패한 작업이 나열될 수 있습니다. 이제 "성공" 상태는 모든 작업이 모든 항목에 성공했음을 의미합니다. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["작업 상태 패널을 보는 방법을 참조하십시오"].



== 2023년 1월 9일(버전 1.19)



=== 중요한 데이터가 포함되어 있고 지나치게 허용적인 파일 차트를 볼 수 있는 기능

Governance 대시보드에는 중요한 데이터(민감한 개인 데이터 및 민감한 개인 데이터 포함)를 포함하고 지나치게 허용적인 파일의 열 지도를 제공하는 새로운 _Sensitive Data 및 Wide Permissions_영역이 추가되었습니다. 이렇게 하면 민감한 데이터와 관련하여 어떤 위험이 있을 수 있는지 확인할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["자세한 정보"].



=== 데이터 조사 페이지에서 3개의 새 필터를 사용할 수 있습니다

새 필터를 사용하여 데이터 조사 페이지에 표시되는 결과를 구체화할 수 있습니다.

* "액세스 권한이 있는 사용자 수" 필터는 특정 수의 사용자에게 열려 있는 파일과 폴더를 표시합니다. 숫자 범위를 선택하여 결과를 구체화할 수 있습니다. 예를 들어 51-100명의 사용자가 액세스할 수 있는 파일을 확인할 수 있습니다.
* 이제 "Created Time(생성 시간)", "Discovered Time(검색 시간)", "Last Modified(마지막 수정)" 및 "Last Accessed(마지막 액세스)" 필터를 사용하여 미리 정의된 날짜 범위를 선택하는 대신 사용자 지정 날짜 범위를 만들 수 있습니다. 예를 들어 "만든 시간", "6개월 이전" 또는 "최근 10일" 내의 "마지막으로 수정한 날짜"가 있는 파일을 찾을 수 있습니다.
* 이제 "파일 경로" 필터를 사용하여 필터링된 쿼리 결과에서 제외할 경로를 지정할 수 있습니다. 특정 데이터를 포함 및 제외하기 위한 경로를 입력하면 BlueXP 분류에서 포함된 경로의 모든 파일을 먼저 찾은 다음 제외된 경로에서 파일을 제거한 다음 결과를 표시합니다.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filtering-data-in-the-data-investigation-page["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하십시오"].



=== BlueXP 분류는 일본어 개인 번호를 식별할 수 있습니다

BlueXP 분류는 일본어 개인 번호(내 번호라고도 함)가 포함된 파일을 식별하고 분류할 수 있습니다. 여기에는 개인 및 회사 내 번호가 모두 포함됩니다. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["BlueXP 분류에서 데이터에서 식별할 수 있는 모든 개인 데이터 유형을 확인하십시오"].



== 2022년 12월 11일(버전 1.18)



=== 사내 설치 기능의 향상

사내 Data Sense 설치를 위해 다음과 같은 개선 사항이 추가되었습니다.

* 이제 사내 호스트에서 설치를 시작하기 전에 몇 가지 추가 사전 요구 사항을 확인합니다. 이렇게 하면 호스트 시스템이 데이터 감지 소프트웨어를 설치할 준비가 100% 되어 있는지 확인할 수 있습니다.
+
** 에 충분한 공간이 있는지 테스트합니다 `/var/lib/docker`, `/tmp`, 및 `/opt`
** 필요한 모든 폴더에 대한 관련 권한을 테스트합니다


* 구성 페이지에서 작업 환경 섹션에 이제 _Working Environment ID_ 및 _Scanner Group_이름이 표시됩니다. 데이터 소스를 스캔하기 위해 추가 처리 성능을 제공하기 위해 여러 데이터 감지 호스트를 사용하려는 경우 작업 환경 ID를 알아야 합니다.
* 또한 구성 페이지에서 새 섹션에는 설정한 스캐너 그룹과 각 그룹에 있는 스캐너 노드가 표시됩니다.


https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["단일 호스트 서버 및 여러 호스트에 Data Sense를 설치하는 방법에 대해 자세히 알아보십시오"].



== 2022년 11월 13일(버전 1.17)



=== SharePoint 온-프레미스 계정 스캔 지원

이제 데이터 센스를 통해 SharePoint Online 계정과 SharePoint 온-프레미스 계정(SharePoint Server)을 모두 검색할 수 있습니다. 자체 서버에 SharePoint를 설치하거나 인터넷에 액세스할 수 없는 사이트에 SharePoint를 설치해야 하는 경우 이제 데이터 센스에서 해당 계정의 사용자 파일을 검색할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["자세한 정보"^].



=== 여러 디렉토리(폴더 또는 공유)를 재검색하는 기능

이제 변경 사항이 시스템에 반영되도록 여러 디렉토리(폴더 또는 공유)를 즉시 재검색할 수 있습니다. 이렇게 하면 특정 데이터를 다른 데이터보다 먼저 다시 검색하게 할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["디렉토리를 다시 검색하는 방법을 참조하십시오"^].



=== 특정 데이터 소스를 스캔하기 위해 사내 "스캐너" 노드를 추가하는 기능

온-프레미스 위치에 데이터 센스를 설치한 경우 특정 데이터 원본을 스캔하기 위해 스캔 처리 성능이 더 필요한 경우 "스캐너" 노드를 더 추가하고 해당 데이터 원본을 스캔하도록 할당할 수 있습니다. 관리자 노드를 설치한 직후 스캐너 노드를 추가하거나 나중에 스캐너 노드를 추가할 수 있습니다.

필요한 경우 스캔 중인 데이터 소스에 물리적으로 가까운 호스트 시스템에 스캐너 노드를 설치할 수 있습니다. 스캐너 노드가 데이터에 가까울수록 데이터 스캔 시 네트워크 대기 시간이 최대한 줄어들기 때문에 성능이 향상됩니다. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["스캐너 노드를 설치하여 추가 데이터 원본을 스캔하는 방법을 알아봅니다"^].



=== 이제 온-프레미스 설치 관리자가 설치를 시작하기 전에 사전 검사를 수행합니다

Linux 시스템에 Data Sense를 설치할 때 설치 관리자는 실제 설치를 시작하기 전에 시스템이 필요한 모든 요구 사항(CPU, RAM, 용량, 네트워킹 등)을 충족하는지 확인합니다. 따라서 * 설치에 시간을 소비하기 전에 * 문제를 파악할 수 있습니다.



== 2022년 9월 6일(버전 1.16)



=== 파일의 변경 사항을 반영하기 위해 저장소를 즉시 다시 검색할 수 있습니다

변경 내용이 시스템에 반영되도록 특정 리포지토리를 즉시 다시 스캔해야 하는 경우 리포지토리를 선택하고 다시 검색할 수 있습니다. 이렇게 하면 특정 데이터를 다른 데이터보다 먼저 다시 검색하게 할 수 있습니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["디렉토리를 다시 검색하는 방법을 참조하십시오"^].



=== 데이터 조사 페이지의 데이터 감지 스캔 상태에 대한 새 필터

“Analysis Status(분석 상태)” 필터를 사용하면 데이터 감지 스캔의 특정 단계에 있는 파일을 나열할 수 있습니다. 옵션을 선택하여 * 첫 번째 스캔 보류 *, * 완료됨 * 스캔 중, * 재스캔 보류 * 또는 * 실패 * 가 스캔되는 파일 목록을 표시할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하십시오"^].



=== 데이터 주제는 이제 스캔에서 발견된 "개인 데이터"의 일부로 간주됩니다

이제 Data Sense는 규정 준수 대시보드에 표시되는 개인 결과의 일부로 데이터 주제를 인식합니다. 또한 조사 페이지에서 검색을 수행할 때 "개인 데이터"에서 "데이터 제목"을 선택하여 데이터 주제가 포함된 파일만 볼 수 있습니다.



=== 이제 데이터 감지 이동 경로 파일은 검색에서 "범주"의 일부로 간주됩니다

이제 Data Sense는 Breadcrumb 파일을 Compliance Dashboard에 나타나는 범주의 일부로 인식합니다. 소스 위치에서 NFS 공유로 파일을 이동할 때 데이터 센스에서 생성되는 파일입니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Breadcrumb 파일을 만드는 방법에 대해 자세히 알아보십시오"^].

또한 조사 페이지에서 검색을 수행할 때 "범주" 아래의 "데이터 감지 브레드크럼"을 선택하여 데이터 감지 브레드크럼 파일만 볼 수 있습니다.



== 2022년 8월 7일(버전 1.15)



=== 뉴질랜드의 5가지 새로운 유형의 개인 데이터는 데이터 센스로 식별됩니다

데이터 센스를 사용하면 다음 유형의 데이터가 포함된 파일을 식별하고 분류할 수 있습니다.

* 뉴질랜드 은행 계좌 번호
* 뉴질랜드 운전면허증 번호
* 뉴질랜드 IRD 번호(세금 ID)
* 뉴질랜드 NHI(National Health Index) 번호
* 뉴질랜드 여권 번호


link:reference-private-data-categories.html#types-of-personal-data["데이터 센스에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하십시오"].



=== 파일이 이동된 이유를 나타내기 위해 Breadcrumb 파일을 추가하는 기능입니다

데이터 감지 기능을 사용하여 소스 파일을 NFS 공유로 이동할 때 이제 이동 파일 위치에 이동 경로 파일을 그대로 둘 수 있습니다. Breadcrumb 파일을 사용하면 파일이 원래 위치에서 이동된 이유를 쉽게 이해할 수 있습니다. 이동된 각 파일에 대해 시스템에서는 이름이 인 소스 위치에 Breadcrumb 파일을 만듭니다 `<filename>-breadcrumb-<date>.txt` 파일이 이동된 위치와 파일을 이동한 사용자를 표시합니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["자세한 정보"^].



=== 디렉터리에 있는 개인 데이터 및 중요한 개인 데이터는 조사 결과에 표시됩니다

이제 데이터 조사 페이지에는 디렉토리(폴더 및 공유) 내에서 찾은 개인 데이터 및 중요한 개인 데이터에 대한 결과가 표시됩니다. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-files-that-contain-personal-data["여기 예를 참조하십시오"^].



=== 성공적으로 분류한 볼륨, 버킷 등의 상태를 봅니다

Data Sense가 스캔(볼륨, 버킷 등)하는 개별 리포지토리를 볼 때 "매핑" 수와 "분류" 수를 확인할 수 있습니다. 모든 데이터에 대해 전체 AI ID가 수행되므로 분류에 시간이 더 오래 걸립니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["이 정보를 보는 방법을 참조하십시오"^].



=== 이제 데이터 센스에서 식별할 수 있는 사용자 지정 패턴을 데이터에 추가할 수 있습니다

데이터 센스에서 향후 검색에서 식별할 수 있는 사용자 지정 "개인 데이터"를 추가하는 방법은 두 가지가 있습니다. 이렇게 하면 중요한 데이터가 조직의 모든 파일에 있는 위치를 전체적으로 파악할 수 있습니다.

* 텍스트 파일에서 사용자 지정 키워드를 추가할 수 있습니다.
* 정규식(regex)을 사용하여 개인 패턴을 추가할 수 있습니다.


이러한 키워드 및 패턴은 데이터 센스에서 이미 사용하는 기존의 미리 정의된 패턴에 추가되며, 결과는 개인 패턴 섹션 아래에 표시됩니다. https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["자세한 정보"^].
