= 버전 1.40
:allow-uri-read: 




=== 버전 1.40

이 BlueXP  분류 릴리스에는 다음 업데이트가 포함됩니다.

.RHEL 9.5 지원
이 릴리스는 Red Hat Enterprise Linux v9.5 및 이전에 지원되는 버전을 지원합니다. 이는 다크 사이트 배포를 포함하여 BlueXP  분류의 수동 온-프레미스 설치에 적용됩니다.

다음 운영 체제는 Podman 컨테이너 엔진을 사용해야 하며 BlueXP  분류 버전 1.30 이상이 필요합니다. Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.

.스캔 우선 순위 지정
스캔 구성 시 가장 중요한 스캔 우선 순위를 지정하여 다른 스캔 전에 수행할 수 있습니다. 이 기능은 작업 환경이 많은 경우 우선 순위가 높은 스캔이 처음에 성공적으로 수행되도록 하려는 경우에 유용합니다.

스캔에는 두 가지 유형이 있습니다.

* * 매핑 전용 스캔 * 은 데이터에 대한 높은 수준의 개요만 제공합니다. 내부 데이터를 보기 위해 파일에 액세스하지 않기 때문에 데이터 소스에서 매핑을 매우 빠르게 수행할 수 있습니다.
* * 지도 및 분류 * 스캔을 통해 데이터를 심층적으로 스캔할 수 있습니다.


매핑 전용 스캔을 사용하여 데이터를 빠르게 스캔하여 더 많은 연구가 필요한 데이터 소스를 식별한 다음 나중에 필요한 데이터 소스 또는 볼륨에 대해서만 맵 및 분류를 활성화할 수 있습니다.

우선 순위는 매핑 전용 스캔에만 할당되며 스캔 맵핑 및 분류에는 할당되지 않습니다.

우선 순위는 기본적으로 1로 설정되며 1에서 10 사이의 숫자로 변경할 수 있습니다. 숫자가 낮을수록 우선 순위가 높습니다. 우선순위를 설정하지 않으면 스캔에 우선순위 5가 지정됩니다.

우선 순위를 변경하려면 다음을 실행합니다.

. BlueXP  classification 메뉴에서 * Configuration * 을 선택합니다.
. 우선 순위를 지정할 자원을 선택합니다.
. 작업... 옵션에서 * 스캔 우선 순위 * 를 선택합니다.


.스캔을 다시 시도하십시오
이 릴리스에서는 실패한 스캔을 다시 시도할 수 있습니다. 이 기능은 네트워크 중단과 같은 일시적인 문제로 인해 검사가 실패한 경우 유용합니다. 재구성하지 않고 스캔을 다시 시도할 수 있습니다.

스캔을 다시 시도하려면 다음을 수행합니다.

. BlueXP  classification 메뉴에서 * Configuration * 을 선택합니다.
. 다음 중 하나를 수행합니다.
+
** 실패한 모든 스캔을 다시 시도하려면 * 모든 스캔 재시도 * 를 선택합니다.
** 특정 스캔을 다시 시도하려면 리소스를 선택하고 Actions... 옵션에서 * Retry scan * 을 선택하십시오.




스캔은 원본 스캔과 동일한 구성으로 재시도합니다. 스캔이 다시 실패하면 필요한 만큼 다시 시도할 수 있습니다.
